---

startDelaySeconds: 10
lowercaseOutputName: false
lowercaseOutputLabelNames: false

whitelistObjectNames:
  # JVM
  - "java.lang:type=Runtime"
  - "java.lang:type=OperatingSystem"
  # Xodus
  - "jetbrains.exodus.env: type=EnvironmentStatistics,*"
  - "jetbrains.exodus.entitystore: type=EntityStoreStatistics,*"
  # YouTrack
  - "jetbrains.youtrack:type=Maintenance,name=Global"
  - "jetbrains.youtrack:type=*,name=BackupManager"
  - "jetbrains.youtrack:type=*,name=UserSessions"
  - "jetbrains.youtrack:type=*,name=HubIntegration"
  - "jetbrains.youtrack:type=*,name=NotificationsSender"
  - "jetbrains.youtrack:type=*,name=JobProcessorsTelemetry"
  - "jetbrains.youtrack:type=*,name=ZendeskIntegration"
  - "jetbrains.youtrack:type=JobProcessor,*"
  - "jetbrains.youtrack:type=JobThreadPool,*"
  - "jetbrains.youtrack:type=Workflow,*"
  - "jetbrains.youtrack:type=TextIndex,*"

rules:
  - pattern: 'java.lang<type=Runtime><>Uptime:'
    name: process_uptime
    help: Total time elapsed since process start in milliseconds
    type: COUNTER

  - pattern: 'java.lang<type=OperatingSystem><>ProcessCpuLoad:'
    name: process_cpu_load
    help: Current process cpu usage share
    type: GAUGE

  - pattern: 'jetbrains.exodus.env< type=EnvironmentStatistics,  location=(.*)><>(\w+):'
    name: youtrack_$2
    labels:
      path: $1
    help: Xodus environment metrics

  - pattern: 'jetbrains.exodus.entitystore< type=EntityStoreStatistics,  location=(.*),  name=teamsysstore><>(\w+):'
    name: youtrack_$2
    labels:
      path: $1
    help: Xodus entity store metrics

  - pattern: 'jetbrains.youtrack<type=Maintenance, name=Global><>(\w+): ([\.\w]+):'
    name: youtrack_version_info
    labels:
      $1: $2
    value: 1.0
    type: GAUGE
    help: Application version info

  # Background jobs metrics flatten out by type and attribute, name as label
  - pattern: 'jetbrains.youtrack<type=(JobProcessor|JobThreadPool), name=(\w+)><>(\w+):'
    name: youtrack_$1_$3
    labels:
      name: $2

  - pattern: 'jetbrains.youtrack<type=Workflow, name=(\w+), script=([\w_\-\/@]+)><>(\w+):'
    name: youtrack_Workflow_$1_$3
    help: Workflow JS metrics
    labels:
      script: $2

  - pattern: 'jetbrains.youtrack<type=TextIndex, name=TextIndexTelemetryMBean><>(\w+):'
    name: youtrack_TextIndex_$1
    help: Text index metrics
