# https://docs.docker.com/compose/compose-file/
# https://docs.docker.com/compose/compose-file/05-services/

services:


  gatling-monitoring:
    image: maven:3.9.9-amazoncorretto-21-debian
    cpu_count: 1
    cpuset: "5-7"
    mem_reservation: 256m
    mem_limit: 512m
    depends_on:
      telegraf:
        condition: service_healthy
      influxdb_v2:
        condition: service_healthy
      youtrack:
        condition: service_healthy
    volumes:
      - "./src:/tmp/gatling/src:ro"
      - "./pom.xml:/tmp/gatling/pom.xml:ro"
      - "./volumes/gatling/repository:/root/.m2/repository"
      - "./tools/perfana:/tools/perfana:ro"
      - "./volumes/gatling/io.netty.native.workdir:/io.netty.native.workdir"
      - "./volumes/gatling/jansi.tmpdir:/jansi.tmpdir"
      - "./volumes/gatling/monitoring:/tmp/gatling/target/load-test-results"
    tmpfs:
      - /tmp
    working_dir: /tmp/gatling
    restart: "no"
    command: mvn test -P monitoring
    networks:
      - youtrack_net

  gatling-issue-generation:
    image: maven:3.9.9-amazoncorretto-21-debian
    cpu_count: 2
    cpuset: "5-7"
    mem_reservation: 2000m
    mem_limit: 3000m
    depends_on:
      telegraf:
        condition: service_healthy
      influxdb_v2:
        condition: service_healthy
      youtrack:
        condition: service_healthy
    volumes:
      - "./src:/tmp/gatling/src:ro"
      - "./pom.xml:/tmp/gatling/pom.xml:ro"
      - "./volumes/gatling/repository:/root/.m2/repository"
      - "./tools/perfana:/tools/perfana:ro"
      - "./volumes/gatling/io.netty.native.workdir:/io.netty.native.workdir"
      - "./volumes/gatling/jansi.tmpdir:/jansi.tmpdir"
      - "./volumes/gatling/issue-generation:/tmp/gatling/target/load-test-results"
      - "./volumes/gatling/big.dataset:/big.dataset:ro"
      - "./datasources:/datasources:ro"
    tmpfs:
      - /tmp
    working_dir: /tmp/gatling
    restart: "no"
    command: bash -x -c "
      echo 'Starting g2i in detached mode, saving PID in variable' &&
      export G2IPID=$$(/tools/perfana/gatling-to-influxdb/g2i-linux-amd64 
        ./target/load-test-results --address http://nginx:8089
        --system-under-test issue_generation --test-environment local --stop-timeout 90
        --database g2i_gatling --password password --username g2i_gatling
        --log /tmp/g2i.log -d | awk '{print $$2}')
      &&
      echo 'Build and execute test' &&
      mvn test -P issue-generation-40-rps
      &&
      echo 'Waiting for parser to safely finish all its work' &&
      sleep 30
      &&
      cat /tmp/g2i.log &&
      echo 'Sending interrupt signal to g2i process' &&
      kill -INT $$G2IPID
      &&
      echo 'Waiting for process to stop safely' &&
      sleep 30
      &&
      echo 'Exiting'
      "
    networks:
      - youtrack_net


networks:
  youtrack_net: