{
 "title": "Grafana self-monitoring over InfluxDB",
 "description": "Use Telegraf to collect metrics, InfluxDB OSS 2.x to store them",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "influx_db", "label": "Influx Server", "query": "influxdb" },
   { "name": "bucket", "label": "DB name", "query": "buckets()" },
   {
    "name": "hostname",
    "query": "from(bucket: \"${bucket}\")\r\n|> range(start: v.timeRangeStart)\r\n|> filter(fn: (r) => r[\"_field\"] == \"grafana_build_info\")\r\n|> keyValues(keyColumns: [\"host\"])\r\n|> group()\r\n|> distinct(column:  \"host\")"
   },
   { "name": "over", "label": "Interval", "query": "10s,1m,5m,10m" }
  ]
 },
 "panels": [
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"process_start_time_seconds\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n    r with _value: \r\n    uint(v:\r\n      duration(v:\r\n        int(v: \r\n          now()\r\n        ) - int(v: \r\n          r._value * 1000.0\r\n        ) * 1000000\r\n      )\r\n    )\r\n  }))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grafana_stat_totals_dashboard\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grafana_stat_total_users\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grafana_stat_total_orgs\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> last()"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"grafana_stat_totals_datasource\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> last()\r\n  |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> sum(column: \"_value\")\r\n"
    }
   ]
  },
  { "title": "CPU, Mem, IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Average CPU Usage over ${over}",
   "type": "timeseries",
   "description": "Average user and system CPU time spent in seconds, summary for ${over} interval",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"process_cpu_seconds_total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> derivative(unit: ${over}, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")\r\n"
    }
   ]
  },
  {
   "title": "Average Memory Usage over ${over}",
   "type": "timeseries",
   "description": "Virtual and Resident memory size in bytes, averages over ${over} interval",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"process_resident_memory_bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> derivative(unit: ${over}, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    },
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"process_virtual_memory_bytes\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> derivative(unit: ${over}, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"process_open_fds\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")\r\n"
    }
   ]
  },
  {
   "title": "Response Codes and Logins",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Response Statuses over ${over}",
     "type": "timeseries",
     "description": "http response status",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_response_status_total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> derivative(unit: ${over}, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
      },
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_page_response_status_total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> derivative(unit: ${over}, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
      },
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_proxy_response_status_total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> derivative(unit: ${over}, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
      }
     ]
    },
    {
     "title": "HTTP Req/Resp over ${over} detailed",
     "type": "timeseries",
     "description": "http request counter",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_http_request_duration_seconds\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> derivative(unit: ${over}, nonNegative: true)\r\n  |> yield(name: \"nonnegative derivative\")"
      }
     ]
    },
    {
     "title": "Login Counts",
     "type": "timeseries",
     "description": "api login counters",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_login_post_total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_login_oauth_total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")\r\n"
      },
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_login_saml_total\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Get Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Get Duration Quantiles",
     "type": "timeseries",
     "description": "summary for dashboard get duration",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_dashboard_get_milliseconds\")\r\n  |> filter(fn: (r) => r[\"_field\"] != \"count\" and r[\"_field\"] != \"sum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Dashboard Get Duration Avg",
     "type": "timeseries",
     "description": "average dashboard get duration over 5m",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_dashboard_get_milliseconds\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\" or r[\"_field\"] == \"sum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 5m, nonNegative: true)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r.count == 0 then 0.0 else r.sum / r.count,\r\n    _field: \"avg\"\r\n  }))\r\n  |> drop(columns: [\"count\",\"sum\"])\r\n  |> yield(name: \"avg\")\r\n  \r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Save Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Save Duration Quantiles",
     "type": "timeseries",
     "description": "summary for dashboard save duration",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_dashboard_save_milliseconds\")\r\n  |> filter(fn: (r) => r[\"_field\"] != \"count\" and r[\"_field\"] != \"sum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Dashboard Save Duration Avg",
     "type": "timeseries",
     "description": "average dashboard save duration over 5m",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_dashboard_save_milliseconds\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\" or r[\"_field\"] == \"sum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 5m, nonNegative: true)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r.count == 0 then 0.0 else r.sum / r.count,\r\n    _field: \"avg\"\r\n  }))\r\n  |> drop(columns: [\"count\",\"sum\"])\r\n  |> yield(name: \"avg\")\r\n  \r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Search Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dashboard Search Duration Quantiles",
     "type": "timeseries",
     "description": "summary for dashboard search duration",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_dashboard_search_milliseconds\")\r\n  |> filter(fn: (r) => r[\"_field\"] != \"count\" and r[\"_field\"] != \"sum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Dashboard Search Duration Avg",
     "type": "timeseries",
     "description": "average dashboard search duration over 5m",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_dashboard_search_milliseconds\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\" or r[\"_field\"] == \"sum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> derivative(unit: 5m, nonNegative: true)\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    r with\r\n    _value: if r.count == 0 then 0.0 else r.sum / r.count,\r\n    _field: \"avg\"\r\n  }))\r\n  |> drop(columns: [\"count\",\"sum\"])\r\n  |> yield(name: \"avg\")\r\n  \r\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Dataproxy Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Dataproxy Request Quantiles",
     "type": "timeseries",
     "description": "summary for dataproxy request duration",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"grafana_api_dataproxy_request_all_milliseconds\")\r\n//  |> filter(fn: (r) => r[\"_field\"] != \"count\" and r[\"_field\"] != \"sum\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)\r\n  |> yield(name: \"mean\")"
      }
     ]
    }
   ]
  }
 ]
}