{
 "title": "Perfana JFR Metrics 0.6-beta",
 "description": "Show events from JFR",
 "tags": [
  "jfr",
  "perfana",
  "perfana-template",
  "Global"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "influxdb" },
   {
    "name": "system_under_test",
    "query": "SHOW TAG VALUES WITH KEY = \"systemUnderTest\""
   },
   {
    "name": "test_environment",
    "query": "SHOW TAG VALUES WITH KEY = \"testEnvironment\" WHERE \"systemUnderTest\" =~ /${system_under_test:regex}/"
   },
   {
    "name": "service",
    "query": "SHOW TAG VALUES WITH KEY = \"service\" WHERE \"systemUnderTest\" =~ /${system_under_test:regex}/ AND \"testEnvironment\" =~ /${test_environment:regex}/"
   },
   {
    "name": "object_size",
    "query": "1 GiByte + : \"bytes\" >= 1024 * 1024 * 1024, 500 MiByte - 1 GiByte + : \"bytes\" >= 500 * 1024 * 1024 AND \"bytes\" < 1024 * 1024 * 1024, 200-500 MiByte : \"bytes\" >= 200 * 1024 * 1024 AND \"bytes\" < 500 * 1024 * 1024, 50-200 MiByte : \"bytes\" >= 50 * 1024 * 1024 AND \"bytes\" < 200 * 1024 * 1024, 10-50 MiByte : \"bytes\" >= 10 * 1024 * 1024 AND \"bytes\" < 50 * 1024 * 1024, up to 10 MiByte : \"bytes\" < 10 * 1024 * 1024"
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "CPU",
     "query": "SELECT max(*) FROM \"CPU\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heap",
     "query": "SELECT max(*) FROM \"heap\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads active",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "query": "SELECT max(*) FROM \"threads\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "bytes per second",
     "measurement": "allocation-rate-bytes",
     "query": "SELECT \"bytes\" FROM \"allocation-rate-bytes\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections (young)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "youngGc",
     "query": "SELECT max(\"duration-ms\") FROM \"youngGc\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections max (young)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "youngGc",
     "query": "SELECT max(\"duration-ms\") FROM \"youngGc\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections total time (young)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "youngGc",
     "query": "SELECT sum(\"duration-ms\") FROM \"youngGc\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections (old)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Old GC duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "oldGc",
     "query": "SELECT max(\"duration-ms\") FROM \"oldGc\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections max (old)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "oldGc",
     "query": "SELECT max(\"duration-ms\") FROM \"oldGc\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Garbage collections total time (old)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "oldGc",
     "query": "SELECT sum(\"duration-ms\") FROM \"oldGc\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Safe points",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Safe point duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "safepoint",
     "query": "SELECT max(\"duration-ms\") FROM \"safepoint\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Safe point max",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "safepoint",
     "query": "SELECT distinct(\"duration-ms\") FROM \"safepoint\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Safe point total time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "measurement": "safepoint",
     "query": "SELECT sum(\"duration-ms\") FROM \"safepoint\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Big allocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "big allocation size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "big-allocations",
     "query": "SELECT distinct(\"bytes\") FROM \"big-allocations\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Big allocation stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "measurement": "big-allocations",
     "query": "SELECT \"bytes\" FROM \"big-allocations\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "measurement": "big-allocations",
     "query": "SELECT \"stacktrace\",\"objectClass\" FROM \"default\".\"big-allocations\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "objectClass" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Large allocation: ${object_size}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "repeat": "object_size"
  },
  {
   "title": "Large allocation samples",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "allocation sample",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "object-allocation-sample",
     "query": "SELECT distinct(\"bytes\") FROM \"object-allocation-sample\" WHERE ${object_size:raw} AND (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Large allocation samples stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "measurement": "object-allocation-sample",
     "query": "SELECT \"stacktrace\", \"objectClass\", \"thread\", \"bytes\" FROM \"object-allocation-sample\" WHERE ${object_size:raw} AND (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "objectClass" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Large allocation samples stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "measurement": "object-allocation-sample",
     "query": "SELECT \"stacktrace\", \"objectClass\", \"thread\", \"bytes\" FROM \"object-allocation-sample\" WHERE ${object_size:raw} AND (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "objectClass" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Large allocation samples stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "measurement": "object-allocation-sample",
     "query": "SELECT \"stacktrace\", \"objectClass\", \"thread\", \"bytes\" FROM \"object-allocation-sample\" WHERE ${object_size:raw} AND (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "objectClass" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Large allocation samples stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "measurement": "object-allocation-sample",
     "query": "SELECT \"stacktrace\", \"bytes\" FROM \"object-allocation-sample\" WHERE ${object_size:raw} AND (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "objectClass" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 } },
  {
   "title": "Java Monitor Enter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 224 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "monitor duration",
     "measurement": "java-monitor-enter",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-enter\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Java Monitor Enter stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 224 },
   "targets": [
    {
     "measurement": "java-monitor-enter",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-enter\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "measurement": "java-monitor-enter",
     "query": "SELECT \"stacktrace\",\"objectClass\" FROM \"default\".\"big-allocations\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ],
      [
       { "params": [ "address" ], "type": "field" }
      ],
      [
       { "params": [ "monitor-class" ], "type": "field" }
      ],
      [
       { "params": [ "previous-owner" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Java Monitor Wait",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "measurement": "java-monitor-wait",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-wait\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Java Monitor Wait stacktraces",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 233 },
   "targets": [
    {
     "measurement": "java-monitor-wait",
     "query": "SELECT \"duration-ns\" FROM \"java-monitor-wait\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration-ns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    },
    {
     "measurement": "java-monitor-wait",
     "query": "SELECT \"stacktrace\",\"objectClass\" FROM \"default\".\"big-allocations\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "stacktrace" ], "type": "field" }
      ],
      [
       { "params": [ "thread" ], "type": "field" }
      ],
      [
       { "params": [ "address" ], "type": "field" }
      ],
      [
       { "params": [ "monitor-class" ], "type": "field" }
      ],
      [
       { "params": [ "notifier" ], "type": "field" }
      ],
      [
       { "params": [ "timeout" ], "type": "field" }
      ],
      [
       { "params": [ "timed-out" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Socket read bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_host $tag_address $tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "address::tag" ], "type": "tag" }
     ],
     "measurement": "socket-read-rate-bytes",
     "query": "SELECT sum(\"bytes\") FROM \"socket-read-rate-bytes\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval), \"port\"::tag, \"host\"::tag, \"address\"::tag",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Socket write bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 242 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_host $tag_address $tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "port::tag" ], "type": "tag" },
      { "params": [ "address::tag" ], "type": "tag" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "socket-write-rate-bytes",
     "query": "SELECT sum(\"bytes\") FROM \"socket-write-rate-bytes\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval), \"port\"::tag, \"address\"::tag, \"host\"::tag fill(null)",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 251 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "classes-loaded",
     "query": "SELECT max(\"loadedClassCount\") FROM \"classes-loaded\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "loadedClassCount" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Resident Set Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 251 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-resident-set-size",
     "query": "SELECT max(*) FROM \"memory-resident-set-size\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Committed per Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT max(\"committed\") FROM \"memory-native\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval), \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Reserved per Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT max(\"reserved\") FROM \"memory-native\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval), \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "reserved" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Committed per Type",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT min(\"committed\"), mean(\"committed\"), max(\"committed\"), max(\"reserved\")/100.0 as \"reserved\" FROM \"memory-native\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Reserved per Type",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 269 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT min(\"reserved\"), mean(\"reserved\"), max(\"reserved\") FROM \"memory-native\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Committed per Type (non Heap)",
   "type": "table",
   "gridPos": { "h": 28, "w": 12, "x": 0, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT min(\"committed\"), mean(\"committed\"), max(\"committed\"), max(\"reserved\")/100.0 as \"reserved\" FROM \"memory-native\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND \"type\"::tag != 'Java Heap' AND $timeFilter GROUP BY \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Native Reserved per Type (non Heap)",
   "type": "table",
   "gridPos": { "h": 28, "w": 12, "x": 12, "y": 279 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native",
     "query": "SELECT min(\"reserved\"), mean(\"reserved\"), max(\"reserved\") FROM \"memory-native\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND \"type\"::tag != 'Java Heap' AND $timeFilter GROUP BY \"type\"::tag fill(null)",
     "select": [
      [
       { "params": [ "committed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Native Memory Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 307 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory-native-total",
     "query": "SELECT max(*) FROM \"memory-native-total\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Thread context switch rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 307 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "alias": "switch rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "thread-context-switch-rate",
     "query": "SELECT max(\"switchRate\") FROM \"thread-context-switch-rate\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "switchRate" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU throttle time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 316 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-cpu-throttling-time",
     "query": "SELECT difference(*) FROM \"container-cpu-throttling-time\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU slices",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 316 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-cpu-throttling-slices",
     "query": "SELECT difference(*) FROM \"container-cpu-throttling-slices\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 325 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-memory-usage",
     "query": "SELECT max(*) FROM \"container-memory-usage\" WHERE (\"service\"::tag =~ /^${service:regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  },
  {
   "title": "Container memory request failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 325 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "measurement": "container-memory-usage-failures",
     "query": "SELECT difference(*) FROM \"container-memory-usage-failures\" WHERE (\"service\"::tag =~ /^${service::regex}$/ AND \"testEnvironment\"::tag =~ /^${test_environment:regex}$/ AND \"systemUnderTest\"::tag =~ /^${system_under_test:regex}$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "service::tag", "operator": "=~", "value": "/^$service$/" },
      { "condition": "AND", "key": "testEnvironment::tag", "operator": "=~", "value": "/^$test_environment$/" },
      { "condition": "AND", "key": "systemUnderTest::tag", "operator": "=~", "value": "/^$system_under_test$/" }
     ]
    }
   ]
  }
 ]
}