{
 "title": "YouTrack Workflows",
 "description": "Dashboard for YouTrack Workflows: 🛡 Rule Guard, ❇️ Rule, 🗓 On Schedule Full\n",
 "tags": [
  "YouTrack Server",
  "YouTrack Workflows"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "offset", "query": "7d : 7d,14d : 14d,21d : 21d" },
   {
    "name": "diff_interval",
    "query": "1h : 1h,2h : 2h,3h : 3h,4h : 4h,5h : 5h,6h : 6h,12h : 12h,1d : 1d,2d : 2d,3d : 3d,4d : 4d,7d : 7d"
   },
   {
    "name": "instance",
    "query": "query_result(sort_desc(    sum by (instance) (increase(    youtrack_UserSessions_ActiveUsers{}[$__range:$__interval]    ))))"
   },
   { "name": "app_start", "label": "Show app start", "query": "✅ Yes : 1,🔳 No : 0" }
  ]
 },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "### Version of <a href=\"https://www.jetbrains.com/youtrack/\" target=\"_blank\" rel=\"author\" title=\"YouTrack. Project management for all your teams\"><img src=\"https://youtrack.jetbrains.com/youtrack-wide-dark.svg\" height=\"30\" /></a>\nDifferent colours 🟩🟨🟦 are different versions.\n\nMove a cursor 👆to the head of the line to get version info.\n"
   }
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (Version) ({__name__=~\"youtrack_version_info|youtrack_version\",  instance=~\"$instance\" })"
    },
    {
     "expr": "avg by (instance, Build) ({__name__=~\"youtrack_version_info|youtrack_version\",  instance=~\"$instance\" })"
    }
   ]
  },
  {
   "title": "Scripts that affect the duration of responses: ❇️ Rule, 🛡 Rule Guard",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 8 }
  },
  {
   "title": "All workflow scripts: ❇️ Rule, 🛡 Rule Guard, 🗓 On Schedule Full",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 }
  },
  { "title": "❇️ Rule", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 10 } },
  {
   "title": "❌ Failed ❇️ Rule (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "❌ Failed count per minute for ❇️ Rule (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_Rule_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✴️ Events ❇️ Rule (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✴️ Events count per minute for ❇️ Rule (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_Rule_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration of ❇️ Rule (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration (per 1 minute) of ❇️ Rule (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration of ❇️ Rule (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration (per 1 hour) of ❇️ Rule (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 3600 * sum(rate(\n    youtrack_Workflow_Rule_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Average Duration of one ❇️ Rule (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n )\n  -\n  (  sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n)\n/\n( sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Average Duration (per request) of one ❇️ Rule (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n )\n  -\n  (  sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n)\n/\n( sum(\n    increase(\n        youtrack_Workflow_Rule_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_Rule_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  { "title": "🛡 Rule Guard", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 46 } },
  {
   "title": "❌ Failed 🛡 Rule Guard (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "❌ Failed count per minute for 🛡 Rule Guard (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_RuleGuard_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✴️ Events 🛡 Rule Guard (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✴️ Events count per minute for 🛡 Rule Guard (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration of 🛡 Rule Guard (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration (per 1 minute) of 🛡 Rule Guard (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration of 🛡 Rule Guard (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration (per 1 hour) of 🛡 Rule Guard (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 3600 * sum(rate(\n    youtrack_Workflow_RuleGuard_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Average Duration of one 🛡 Rule Guard (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n )\n  -\n  (  sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n)\n/\n( sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Average Duration (per request) of one 🛡 Rule Guard (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n )\n  -\n  (  sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n)\n/\n( sum(\n    increase(\n        youtrack_Workflow_RuleGuard_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_RuleGuard_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  { "title": "🗓 On Schedule Full", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 82 } },
  {
   "title": "❌ Failed 🗓 On Schedule Full (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "❌ Failed count per minute for 🗓 On Schedule Full (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_FailedCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✴️ Events 🗓 On Schedule Full (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✴️ Events count per minute for 🗓 On Schedule Full (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalCount{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration of 🗓 On Schedule Full (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration (per 1 minute) of 🗓 On Schedule Full (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 60 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration of 🗓 On Schedule Full (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Duration (per 1 hour) of 🗓 On Schedule Full (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:]\n))\n )\n  -\n  (  3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n)\n/\n( 3600 * sum(rate(\n    youtrack_Workflow_OnScheduleFull_TotalDuration{\n         instance=~\"$instance\"\n    }[$__interval:] offset ${offset}\n))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Average Duration of one 🗓 On Schedule Full (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n )\n  -\n  (  sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n)\n/\n( sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🕒 Average Duration (per request) of one 🗓 On Schedule Full (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:]\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:]\n    )>0)\n)\n )\n  -\n  (  sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n)\n/\n( sum(\n    increase(\n        youtrack_Workflow_OnScheduleFull_TotalDuration{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    ) /\n    (increase(\n        youtrack_Workflow_OnScheduleFull_TotalCount{\n             instance=~\"$instance\"\n        }[$__interval:] offset ${offset}\n    )>0)\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  }
 ]
}