{
 "title": "YouTrack Process",
 "description": "Dashboard for YouTrack based processes\n",
 "tags": [ "YouTrack Server" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "offset", "query": "7d : 7d,14d : 14d,21d : 21d" },
   {
    "name": "diff_interval",
    "query": "1h : 1h,2h : 2h,3h : 3h,4h : 4h,5h : 5h,6h : 6h,12h : 12h,1d : 1d,2d : 2d,3d : 3d,4d : 4d,7d : 7d"
   },
   {
    "name": "instance",
    "query": "query_result(sort_desc(    sum by (instance) (    youtrack_UtilizationPercent{}    ) > 0))"
   },
   { "name": "app_start", "label": "Show app start", "query": "✅ Yes : 1,🔳 No : 0" }
  ]
 },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "### Version\nDifferent colours 🟩🟨🟦 are different versions.\n\nMove a cursor 👆to the head of the line to get version info.\n"
   }
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (Version) (youtrack_version_info{  instance=~\"$instance\" })"
    },
    {
     "expr": "avg by (instance, Build) (youtrack_version_info{  instance=~\"$instance\" })"
    }
   ]
  },
  { "title": "🧮 CPU", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 8 } },
  {
   "title": "🧮 CPU % (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( 100 * process_cpu_load{  instance=~\"$instance\" } )\n  -\n  ( 100 * process_cpu_load{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( 100 * process_cpu_load{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🧮 CPU % (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * process_cpu_load{  instance=~\"$instance\" } offset ${offset}",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * process_cpu_load{  instance=~\"$instance\" }",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( 100 * process_cpu_load{  instance=~\"$instance\" } )\n  -\n  ( 100 * process_cpu_load{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( 100 * process_cpu_load{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🧮 CPU Cores (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval])) )\n  -\n  ( sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval] offset ${offset})) )\n)\n/\n( round( sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval] offset ${offset})) , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🧮 CPU Cores (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval] offset ${offset}))",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval]))",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval])) )\n  -\n  ( sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval] offset ${offset})) )\n)\n/\n( round( sum(rate(process_cpu_seconds_total{  instance=~\"$instance\" }[$__rate_interval] offset ${offset})) , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  { "title": "🖼 Memory", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 23 } },
  {
   "title": "🖼 Resident Memory (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( process_resident_memory_bytes{  instance=~\"$instance\" } )\n  -\n  ( process_resident_memory_bytes{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( process_resident_memory_bytes{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🖼 Resident Memory (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "process_resident_memory_bytes{  instance=~\"$instance\" } offset ${offset}",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "process_resident_memory_bytes{  instance=~\"$instance\" }",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( process_resident_memory_bytes{  instance=~\"$instance\" } )\n  -\n  ( process_resident_memory_bytes{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( process_resident_memory_bytes{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🖼 Virtual Memory (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( process_virtual_memory_bytes{  instance=~\"$instance\" } )\n  -\n  ( process_virtual_memory_bytes{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( process_virtual_memory_bytes{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🖼 Virtual Memory (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "process_virtual_memory_bytes{  instance=~\"$instance\" } offset ${offset}",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "process_virtual_memory_bytes{  instance=~\"$instance\" }",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( process_virtual_memory_bytes{  instance=~\"$instance\" } )\n  -\n  ( process_virtual_memory_bytes{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( process_virtual_memory_bytes{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  { "title": "🗂 File Descriptors", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 24, "y": 38 } },
  {
   "title": "🗂 FDS (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( process_open_fds{  instance=~\"$instance\" } )\n  -\n  ( process_open_fds{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( process_open_fds{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🗂 FDS (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "process_open_fds{  instance=~\"$instance\" } offset ${offset}",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "process_open_fds{  instance=~\"$instance\" }",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( process_open_fds{  instance=~\"$instance\" } )\n  -\n  ( process_open_fds{  instance=~\"$instance\" } offset ${offset} )\n)\n/\n( round( process_open_fds{  instance=~\"$instance\" } offset ${offset} , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  }
 ]
}