{
 "title": "YouTrack HubIntegration",
 "description": "YouTrack HubIntegration metrics:\n⚙️ Received, ✅ Processed, ⛔️ Ignored, ⌛️ Pending, ❌ Failed,\n",
 "tags": [
  "YouTrack Server",
  "HubIntegration"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "offset", "query": "7d : 7d,14d : 14d,21d : 21d" },
   {
    "name": "diff_interval",
    "query": "1h : 1h,2h : 2h,3h : 3h,4h : 4h,5h : 5h,6h : 6h,12h : 12h,1d : 1d,2d : 2d,3d : 3d,4d : 4d,7d : 7d"
   },
   {
    "name": "instance",
    "query": "query_result(sort_desc(    sum by (instance) (    youtrack_UtilizationPercent{}    ) > 0))"
   },
   { "name": "app_start", "label": "Show app start", "query": "✅ Yes : 1,🔳 No : 0" }
  ]
 },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "### Version\nDifferent colours 🟩🟨🟦 are different versions.\n\nMove a cursor 👆to the head of the line to get version info.\n"
   }
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (Version) (youtrack_version_info{  instance=~\"$instance\" })"
    },
    {
     "expr": "avg by (instance, Build) (youtrack_version_info{  instance=~\"$instance\" })"
    }
   ]
  },
  {
   "title": "ℹ️ Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 8 },
   "collapsed": true
  },
  {
   "title": "YouTrack HubIntegration: ⚙️ Received, ⌛️ Pending",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 }
  },
  {
   "title": "⚙️ Received (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⚙️ Received (per 1 minute) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsReceived{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⌛️ Pending (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  })\n )\n  -\n  ( avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  } offset ${offset})\n )\n)\n/\n( round( avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  } offset ${offset})\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⌛️ Pending (average Queue lenght) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  } offset ${offset})\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  })\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  })\n )\n  -\n  ( avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  } offset ${offset})\n )\n)\n/\n( round( avg(youtrack_HubIntegration_HubEventsPending{ type=\"Hub\", instance=~\"$instance\"  } offset ${offset})\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "YouTrack HubIntegration (percents): ⛔️ Ignored, ✅ Processed, ❌ Failed",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 24 }
  },
  {
   "title": "⛔️ % Ignored (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⛔️ % Ignored: skip all events caused by internal actions (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✅ % Processed (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✅ % Processed (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "❌ % Failed (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "❌ % Failed: see error messages \"Got exception while processing Ring event\" in logs (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n) / (\n( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "YouTrack HubIntegration (events per minute): ⛔️ Ignored, ✅ Processed, ❌ Failed",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 46 }
  },
  {
   "title": "⛔️ Ignored (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⛔️ Ignored (per 1 minute): skip all events caused by internal actions (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsIgnored{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✅ Processed (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✅ Processed (per 1 minute) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsProcessed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "❌ Failed (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "❌ Failed (per 1 minute): see error messages \"Got exception while processing Ring event\" in logs (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval]))\n* 60 * 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_HubIntegration_HubEventsFailed{ type=\"Hub\", instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 60 * 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  }
 ]
}