{
 "title": "Xodus storage: 🛠 Execute → ✳️ Started | ⛔️ Not Started",
 "description": "YouTrack Xodus entity store metrics (DB):\n⚙️ Cached Jobs →\n✅ Queued →\n(🟡 Consistent | 🟠 Non Consistent) →\n🛠️ Execute →\n✳️ Started | ⛔️ Not Started\n",
 "tags": [
  "YouTrack Server",
  "Xodus",
  "Xodus Entity",
  "🛠️ Execute",
  "✳️ Started",
  "⛔️ Not Started"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "offset", "query": "7d : 7d,14d : 14d,21d : 21d" },
   {
    "name": "diff_interval",
    "query": "1h : 1h,2h : 2h,3h : 3h,4h : 4h,5h : 5h,6h : 6h,12h : 12h,1d : 1d,2d : 2d,3d : 3d,4d : 4d,7d : 7d"
   },
   {
    "name": "instance",
    "query": "query_result(sort_desc(    sum by (instance) (    youtrack_UtilizationPercent{}    ) > 0))"
   },
   { "name": "app_start", "label": "Show app start", "query": "✅ Yes : 1,🔳 No : 0" }
  ]
 },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "### Version\nDifferent colours 🟩🟨🟦 are different versions.\n\nMove a cursor 👆to the head of the line to get version info.\n"
   }
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (Version) (youtrack_version_info{  instance=~\"$instance\" })"
    },
    {
     "expr": "avg by (instance, Build) (youtrack_version_info{  instance=~\"$instance\" })"
    }
   ]
  },
  {
   "title": "ℹ️ Info: ⚙️ Cached Jobs → ✅ Queued → (🟡|🟠) → 🛠 Execute → ✳️ Started | ⛔️ Not Started",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 8 }
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "<img src='https://polarnik.github.io/youtrack-monitoring/Execute.png' style='height: 100%' />"
   }
  },
  {
   "title": "⚙️ Cached Jobs → ✅ Queued → (🟡|🟠) → 🛠 Execute → ✳️ Started | ⛔️ Not Started",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 16 }
  },
  {
   "title": "🛠 Execute (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n )\n  -\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n )\n)\n/\n( round( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🛠 Execute (per 1 second) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n )\n  -\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n )\n)\n/\n( round( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✳️ Started (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✳️ Started (per 1 second) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⛔️ Not Started (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⛔️ Not Started (per 1 second) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n )\n  -\n  ( sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n )\n)\n/\n( round( sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✳️ % Started (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "✳️ % Started (100 * ✳️ Started / 🛠 Execute) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\n    sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⛔️ % Not Started (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⛔️ % Not Started (100 * ⛔️ Not Started / 🛠 Execute) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n/\n(($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__rate_interval])) < 0)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval]))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n  -\n  ( 100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n )\n)\n/\n( round( 100 * (\n    sum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n)\n/ (\n   ( sum(increase(youtrack_TotalCachingJobsStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n+\nsum(increase(youtrack_TotalCachingJobsNotStarted{  instance=~\"$instance\"  }[$__rate_interval] offset ${offset}))\n* 1000 / $__rate_interval_ms\n\n ) != 0\n)\n , 0.0001) != 0 )\n",
     "legendFormat": "diff"
    }
   ]
  }
 ]
}