{
 "title": "Xodus storage: 🚫️ Interrupted → ⌛️ Obsolete | ⏰ Overdue",
 "description": "YouTrack Xodus entity store metrics (DB):\n⚙️ Cached Jobs →\n✅ Queued →\n(🟡 Consistent | 🟠 Non Consistent) →\n🛠 Execute →\n✳️ Started →\n🚫️ Interrupted →\n⌛️ Obsolete | ⏰ Overdue\n",
 "tags": [
  "YouTrack Server",
  "Xodus",
  "Xodus Entity",
  "🚫️ Interrupted",
  "⌛️ Obsolete",
  "⏰ Overdue"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "offset", "query": "7d : 7d,14d : 14d,21d : 21d" },
   {
    "name": "diff_interval",
    "query": "1h : 1h,2h : 2h,3h : 3h,4h : 4h,5h : 5h,6h : 6h,12h : 12h,1d : 1d,2d : 2d,3d : 3d,4d : 4d,7d : 7d"
   },
   {
    "name": "instance",
    "query": "query_result(sort_desc(    sum by (instance) (increase(    youtrack_UserSessions_ActiveUsers{}[$__range:$__interval]    ))))"
   },
   { "name": "app_start", "label": "Show app start", "query": "✅ Yes : 1,🔳 No : 0" }
  ]
 },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": {
    "content": "### Version of <a href=\"https://www.jetbrains.com/youtrack/\" target=\"_blank\" rel=\"author\" title=\"YouTrack. Project management for all your teams\"><img src=\"https://youtrack.jetbrains.com/youtrack-wide-dark.svg\" height=\"30\" /></a>\nDifferent colours 🟩🟨🟦 are different versions.\n\nMove a cursor 👆to the head of the line to get version info.\n"
   }
  },
  {
   "title": "Version",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (Version) ({__name__=~\"youtrack_version_info|youtrack_version\",  instance=~\"$instance\" })"
    },
    {
     "expr": "avg by (instance, Build) ({__name__=~\"youtrack_version_info|youtrack_version\",  instance=~\"$instance\" })"
    }
   ]
  },
  {
   "title": "ℹ️ Info: 🚫️ Interrupted → ⌛️ Obsolete | ⏰ Overdue",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 8 }
  },
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": {
    "content": "<img src='https://polarnik.github.io/youtrack-monitoring/Execute-Started-Interrupted.png' style='height: 100%' />"
   }
  },
  {
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": {
    "content": "%%{ init: { 'flowchart': { 'curve': 'monotoneX' } } }%%\nflowchart LR\n    A(⚙️ Cached Jobs) ==> B(✅ Queued)\n    A(⚙️ Cached Jobs) -.-> C(❌ Non Queued)\n    B ==> D(🟡 Consistent)\n    B ==> E(🟠 Non Consistent)\n    D ==> F(🛠 Execute)\n    E ==> F\n    F ==> G(✳️ Started)\n    F -.-> H(⛔️ Not Started)\n    G -.-> I(↩️ Retried)\n    G ==> J(❎ Completed)\n    G -.-> K(🚫️ Interrupted)\n    I -.-> L(🟡 Consistent)\n    I -.-> M(🟠 Non Consistent)\n    K -.-> N(⌛️ Obsolete)\n    K -.-> O(⏰ Overdue)"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "🚫️ Interrupted → ⌛️ Obsolete | ⏰ Overdue",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 24, "y": 17 }
  },
  {
   "title": "🚫️ Interrupted (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n )\n  -\n  (  sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n)\n/\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "🚫️ Interrupted (per 1 second) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n )\n  -\n  (  sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n)\n/\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⌛️ Obsolete (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:]))\n )\n  -\n  (  sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n)\n/\n( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⌛️ Obsolete (per 1 second) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:]))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:]))\n )\n  -\n  (  sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n)\n/\n( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⏰ Overdue (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:]))\n )\n  -\n  (  sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n)\n/\n( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⏰ Overdue (per 1 second) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:]))\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:]))\n )\n  -\n  (  sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n)\n/\n( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⌛️ % Obsolete (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:]))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n ) != 0\n)\n )\n  -\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n)\n/\n( 100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⌛️ % Obsolete (100 * ⌛️ Obsolete / 🚫️ Interrupted) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:]))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n ) != 0\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:]))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n ) != 0\n)\n )\n  -\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n)\n/\n( 100 * ( sum(rate(youtrack_TotalCachingJobsObsolete{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⏰ % Overdue (last $diff_interval vs $offset ago)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:]))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n ) != 0\n)\n )\n  -\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n)\n/\n( 100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  },
  {
   "title": "⏰ % Overdue (100 * ⏰ Overdue / 🚫️ Interrupted) (🟥 current vs 🟦 prev)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n  /\n  (($app_start * delta({__name__=~\"process_uptime.*\",  instance=~\"$instance\" }[$__interval:])) < 0)\n)\n",
     "legendFormat": "app start"
    },
    {
     "expr": "100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n",
     "legendFormat": "prev ($offset)"
    },
    {
     "expr": "100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:]))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n ) != 0\n)\n",
     "legendFormat": "current"
    },
    {
     "expr": "100 * (\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:]))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:]))\n ) != 0\n)\n )\n  -\n  (  100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n)\n/\n( 100 * ( sum(rate(youtrack_TotalCachingJobsOverdue{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n )\n/ (\n( sum(rate(youtrack_TotalCachingJobsInterrupted{  instance=~\"$instance\" }[$__interval:] offset ${offset}))\n ) != 0\n)\n )\n",
     "legendFormat": "diff"
    }
   ]
  }
 ]
}