/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;
import java.util.Objects;

/**
 * Shows if the board has any configuration problems.
 */
@Schema(description = "Shows if the board has any configuration problems.")


public class AgileStatus {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("valid")
    private final Boolean valid = null;

    @SerializedName("hasJobs")
    private final Boolean hasJobs = null;

    @SerializedName("errors")
    private final List<String> errors = null;

    @SerializedName("warnings")
    private final List<String> warnings = null;

    @SerializedName("$type")
    private String $type = null;

    public AgileStatus() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    /**
     * Get valid
     *
     * @return valid
     **/
    @Schema(description = "")
    public Boolean isValid() {
        return valid;
    }

    /**
     * Get hasJobs
     *
     * @return hasJobs
     **/
    @Schema(description = "")
    public Boolean isHasJobs() {
        return hasJobs;
    }

    /**
     * Get errors
     *
     * @return errors
     **/
    @Schema(description = "")
    public List<String> getErrors() {
        return errors;
    }

    /**
     * Get warnings
     *
     * @return warnings
     **/
    @Schema(description = "")
    public List<String> getWarnings() {
        return warnings;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AgileStatus agileStatus = (AgileStatus) o;
        return Objects.equals(this.id, agileStatus.id) &&
                Objects.equals(this.valid, agileStatus.valid) &&
                Objects.equals(this.hasJobs, agileStatus.hasJobs) &&
                Objects.equals(this.errors, agileStatus.errors) &&
                Objects.equals(this.warnings, agileStatus.warnings) &&
                Objects.equals(this.$type, agileStatus.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, valid, hasJobs, errors, warnings, $type);
    }


    @Override
    public String toString() {

        String sb = "class AgileStatus {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    valid: " + toIndentedString(valid) + "\n" +
                "    hasJobs: " + toIndentedString(hasJobs) + "\n" +
                "    errors: " + toIndentedString(errors) + "\n" +
                "    warnings: " + toIndentedString(warnings) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
