/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * ArticleAttachment
 */


public class ArticleAttachment {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("author")
    private User author = null;

    @SerializedName("created")
    private final Long created = null;

    @SerializedName("updated")
    private final Long updated = null;

    @SerializedName("size")
    private final Long size = null;

    @SerializedName("extension")
    private final String extension = null;

    @SerializedName("charset")
    private final String charset = null;

    @SerializedName("mimeType")
    private final String mimeType = null;

    @SerializedName("metaData")
    private final String metaData = null;

    @SerializedName("draft")
    private final Boolean draft = null;

    @SerializedName("removed")
    private final Boolean removed = null;

    @SerializedName("base64Content")
    private String base64Content = null;

    @SerializedName("url")
    private final String url = null;

    @SerializedName("visibility")
    private Visibility visibility = null;

    @SerializedName("article")
    private BaseArticle article = null;

    @SerializedName("comment")
    private ArticleComment comment = null;

    @SerializedName("$type")
    private String $type = null;

    public ArticleAttachment() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public ArticleAttachment name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ArticleAttachment author(User author) {
        this.author = author;
        return this;
    }

    /**
     * Get author
     *
     * @return author
     **/
    @Schema(description = "")
    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    /**
     * Get created
     *
     * @return created
     **/
    @Schema(description = "")
    public Long getCreated() {
        return created;
    }

    /**
     * Get updated
     *
     * @return updated
     **/
    @Schema(description = "")
    public Long getUpdated() {
        return updated;
    }

    /**
     * Get size
     *
     * @return size
     **/
    @Schema(description = "")
    public Long getSize() {
        return size;
    }

    /**
     * Get extension
     *
     * @return extension
     **/
    @Schema(description = "")
    public String getExtension() {
        return extension;
    }

    /**
     * Get charset
     *
     * @return charset
     **/
    @Schema(description = "")
    public String getCharset() {
        return charset;
    }

    /**
     * Get mimeType
     *
     * @return mimeType
     **/
    @Schema(description = "")
    public String getMimeType() {
        return mimeType;
    }

    /**
     * Get metaData
     *
     * @return metaData
     **/
    @Schema(description = "")
    public String getMetaData() {
        return metaData;
    }

    /**
     * Get draft
     *
     * @return draft
     **/
    @Schema(description = "")
    public Boolean isDraft() {
        return draft;
    }

    /**
     * Get removed
     *
     * @return removed
     **/
    @Schema(description = "")
    public Boolean isRemoved() {
        return removed;
    }

    public ArticleAttachment base64Content(String base64Content) {
        this.base64Content = base64Content;
        return this;
    }

    /**
     * Get base64Content
     *
     * @return base64Content
     **/
    @Schema(description = "")
    public String getBase64Content() {
        return base64Content;
    }

    public void setBase64Content(String base64Content) {
        this.base64Content = base64Content;
    }

    /**
     * Get url
     *
     * @return url
     **/
    @Schema(description = "")
    public String getUrl() {
        return url;
    }

    public ArticleAttachment visibility(Visibility visibility) {
        this.visibility = visibility;
        return this;
    }

    /**
     * Get visibility
     *
     * @return visibility
     **/
    @Schema(description = "")
    public Visibility getVisibility() {
        return visibility;
    }

    public void setVisibility(Visibility visibility) {
        this.visibility = visibility;
    }

    public ArticleAttachment article(BaseArticle article) {
        this.article = article;
        return this;
    }

    /**
     * Get article
     *
     * @return article
     **/
    @Schema(description = "")
    public BaseArticle getArticle() {
        return article;
    }

    public void setArticle(BaseArticle article) {
        this.article = article;
    }

    public ArticleAttachment comment(ArticleComment comment) {
        this.comment = comment;
        return this;
    }

    /**
     * Get comment
     *
     * @return comment
     **/
    @Schema(description = "")
    public ArticleComment getComment() {
        return comment;
    }

    public void setComment(ArticleComment comment) {
        this.comment = comment;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ArticleAttachment articleAttachment = (ArticleAttachment) o;
        return Objects.equals(this.id, articleAttachment.id) &&
                Objects.equals(this.name, articleAttachment.name) &&
                Objects.equals(this.author, articleAttachment.author) &&
                Objects.equals(this.created, articleAttachment.created) &&
                Objects.equals(this.updated, articleAttachment.updated) &&
                Objects.equals(this.size, articleAttachment.size) &&
                Objects.equals(this.extension, articleAttachment.extension) &&
                Objects.equals(this.charset, articleAttachment.charset) &&
                Objects.equals(this.mimeType, articleAttachment.mimeType) &&
                Objects.equals(this.metaData, articleAttachment.metaData) &&
                Objects.equals(this.draft, articleAttachment.draft) &&
                Objects.equals(this.removed, articleAttachment.removed) &&
                Objects.equals(this.base64Content, articleAttachment.base64Content) &&
                Objects.equals(this.url, articleAttachment.url) &&
                Objects.equals(this.visibility, articleAttachment.visibility) &&
                Objects.equals(this.article, articleAttachment.article) &&
                Objects.equals(this.comment, articleAttachment.comment) &&
                Objects.equals(this.$type, articleAttachment.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, author, created, updated, size, extension, charset, mimeType, metaData, draft, removed, base64Content, url, visibility, article, comment, $type);
    }


    @Override
    public String toString() {

        String sb = "class ArticleAttachment {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    author: " + toIndentedString(author) + "\n" +
                "    created: " + toIndentedString(created) + "\n" +
                "    updated: " + toIndentedString(updated) + "\n" +
                "    size: " + toIndentedString(size) + "\n" +
                "    extension: " + toIndentedString(extension) + "\n" +
                "    charset: " + toIndentedString(charset) + "\n" +
                "    mimeType: " + toIndentedString(mimeType) + "\n" +
                "    metaData: " + toIndentedString(metaData) + "\n" +
                "    draft: " + toIndentedString(draft) + "\n" +
                "    removed: " + toIndentedString(removed) + "\n" +
                "    base64Content: " + toIndentedString(base64Content) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "    visibility: " + toIndentedString(visibility) + "\n" +
                "    article: " + toIndentedString(article) + "\n" +
                "    comment: " + toIndentedString(comment) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
