/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Default settings for the build-type field.
 */
@Schema(description = "Default settings for the build-type field.")


public class BuildBundleCustomFieldDefaults extends BundleCustomFieldDefaults {
    @SerializedName("id")
    private final String buildBundleCustomFieldDefaultsId = null;

    @SerializedName("bundle")
    private BuildBundle bundle = null;

    @SerializedName("defaultValues")
    private List<BuildBundleElement> defaultValues = null;

    /**
     * Get buildBundleCustomFieldDefaultsId
     *
     * @return buildBundleCustomFieldDefaultsId
     **/
    @Schema(description = "")
    public String getBuildBundleCustomFieldDefaultsId() {
        return buildBundleCustomFieldDefaultsId;
    }

    public BuildBundleCustomFieldDefaults bundle(BuildBundle bundle) {
        this.bundle = bundle;
        return this;
    }

    /**
     * Get bundle
     *
     * @return bundle
     **/
    @Schema(description = "")
    public BuildBundle getBundle() {
        return bundle;
    }

    public void setBundle(BuildBundle bundle) {
        this.bundle = bundle;
    }

    public BuildBundleCustomFieldDefaults defaultValues(List<BuildBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
        return this;
    }

    public BuildBundleCustomFieldDefaults addDefaultValuesItem(BuildBundleElement defaultValuesItem) {
        if (this.defaultValues == null) {
            this.defaultValues = new ArrayList<BuildBundleElement>();
        }
        this.defaultValues.add(defaultValuesItem);
        return this;
    }

    /**
     * Get defaultValues
     *
     * @return defaultValues
     **/
    @Schema(description = "")
    public List<BuildBundleElement> getDefaultValues() {
        return defaultValues;
    }

    public void setDefaultValues(List<BuildBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BuildBundleCustomFieldDefaults buildBundleCustomFieldDefaults = (BuildBundleCustomFieldDefaults) o;
        return Objects.equals(this.buildBundleCustomFieldDefaultsId, buildBundleCustomFieldDefaults.buildBundleCustomFieldDefaultsId) &&
                Objects.equals(this.bundle, buildBundleCustomFieldDefaults.bundle) &&
                Objects.equals(this.defaultValues, buildBundleCustomFieldDefaults.defaultValues) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(buildBundleCustomFieldDefaultsId, bundle, defaultValues, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class BuildBundleCustomFieldDefaults {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    buildBundleCustomFieldDefaultsId: " + toIndentedString(buildBundleCustomFieldDefaultsId) + "\n" +
                "    bundle: " + toIndentedString(bundle) + "\n" +
                "    defaultValues: " + toIndentedString(defaultValues) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
