/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents a field value in YouTrack.
 */
@Schema(description = "Represents a field value in YouTrack.")


public class BundleElement {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("bundle")
    private Bundle bundle = null;

    @SerializedName("description")
    private String description = null;

    @SerializedName("archived")
    private Boolean archived = null;

    @SerializedName("ordinal")
    private Integer ordinal = null;

    @SerializedName("color")
    private FieldStyle color = null;

    @SerializedName("hasRunningJob")
    private final Boolean hasRunningJob = null;

    @SerializedName("$type")
    private String $type = null;

    public BundleElement() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public BundleElement name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BundleElement bundle(Bundle bundle) {
        this.bundle = bundle;
        return this;
    }

    /**
     * Get bundle
     *
     * @return bundle
     **/
    @Schema(description = "")
    public Bundle getBundle() {
        return bundle;
    }

    public void setBundle(Bundle bundle) {
        this.bundle = bundle;
    }

    public BundleElement description(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @Schema(description = "")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BundleElement archived(Boolean archived) {
        this.archived = archived;
        return this;
    }

    /**
     * Get archived
     *
     * @return archived
     **/
    @Schema(description = "")
    public Boolean isArchived() {
        return archived;
    }

    public void setArchived(Boolean archived) {
        this.archived = archived;
    }

    public BundleElement ordinal(Integer ordinal) {
        this.ordinal = ordinal;
        return this;
    }

    /**
     * Get ordinal
     *
     * @return ordinal
     **/
    @Schema(description = "")
    public Integer getOrdinal() {
        return ordinal;
    }

    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }

    public BundleElement color(FieldStyle color) {
        this.color = color;
        return this;
    }

    /**
     * Get color
     *
     * @return color
     **/
    @Schema(description = "")
    public FieldStyle getColor() {
        return color;
    }

    public void setColor(FieldStyle color) {
        this.color = color;
    }

    /**
     * Get hasRunningJob
     *
     * @return hasRunningJob
     **/
    @Schema(description = "")
    public Boolean isHasRunningJob() {
        return hasRunningJob;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BundleElement bundleElement = (BundleElement) o;
        return Objects.equals(this.id, bundleElement.id) &&
                Objects.equals(this.name, bundleElement.name) &&
                Objects.equals(this.bundle, bundleElement.bundle) &&
                Objects.equals(this.description, bundleElement.description) &&
                Objects.equals(this.archived, bundleElement.archived) &&
                Objects.equals(this.ordinal, bundleElement.ordinal) &&
                Objects.equals(this.color, bundleElement.color) &&
                Objects.equals(this.hasRunningJob, bundleElement.hasRunningJob) &&
                Objects.equals(this.$type, bundleElement.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, bundle, description, archived, ordinal, color, hasRunningJob, $type);
    }


    @Override
    public String toString() {

        String sb = "class BundleElement {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    bundle: " + toIndentedString(bundle) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    archived: " + toIndentedString(archived) + "\n" +
                "    ordinal: " + toIndentedString(ordinal) + "\n" +
                "    color: " + toIndentedString(color) + "\n" +
                "    hasRunningJob: " + toIndentedString(hasRunningJob) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
