/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * CustomFieldDefaults
 */


public class CustomFieldDefaults {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("canBeEmpty")
    private Boolean canBeEmpty = null;

    @SerializedName("emptyFieldText")
    private String emptyFieldText = null;

    @SerializedName("isPublic")
    private Boolean isPublic = null;

    @SerializedName("parent")
    private CustomField parent = null;

    @SerializedName("$type")
    private String $type = null;

    public CustomFieldDefaults() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public CustomFieldDefaults canBeEmpty(Boolean canBeEmpty) {
        this.canBeEmpty = canBeEmpty;
        return this;
    }

    /**
     * Get canBeEmpty
     *
     * @return canBeEmpty
     **/
    @Schema(description = "")
    public Boolean isCanBeEmpty() {
        return canBeEmpty;
    }

    public void setCanBeEmpty(Boolean canBeEmpty) {
        this.canBeEmpty = canBeEmpty;
    }

    public CustomFieldDefaults emptyFieldText(String emptyFieldText) {
        this.emptyFieldText = emptyFieldText;
        return this;
    }

    /**
     * Get emptyFieldText
     *
     * @return emptyFieldText
     **/
    @Schema(description = "")
    public String getEmptyFieldText() {
        return emptyFieldText;
    }

    public void setEmptyFieldText(String emptyFieldText) {
        this.emptyFieldText = emptyFieldText;
    }

    public CustomFieldDefaults isPublic(Boolean isPublic) {
        this.isPublic = isPublic;
        return this;
    }

    /**
     * Get isPublic
     *
     * @return isPublic
     **/
    @Schema(description = "")
    public Boolean isIsPublic() {
        return isPublic;
    }

    public void setIsPublic(Boolean isPublic) {
        this.isPublic = isPublic;
    }

    public CustomFieldDefaults parent(CustomField parent) {
        this.parent = parent;
        return this;
    }

    /**
     * Get parent
     *
     * @return parent
     **/
    @Schema(description = "")
    public CustomField getParent() {
        return parent;
    }

    public void setParent(CustomField parent) {
        this.parent = parent;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomFieldDefaults customFieldDefaults = (CustomFieldDefaults) o;
        return Objects.equals(this.id, customFieldDefaults.id) &&
                Objects.equals(this.canBeEmpty, customFieldDefaults.canBeEmpty) &&
                Objects.equals(this.emptyFieldText, customFieldDefaults.emptyFieldText) &&
                Objects.equals(this.isPublic, customFieldDefaults.isPublic) &&
                Objects.equals(this.parent, customFieldDefaults.parent) &&
                Objects.equals(this.$type, customFieldDefaults.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, canBeEmpty, emptyFieldText, isPublic, parent, $type);
    }


    @Override
    public String toString() {

        String sb = "class CustomFieldDefaults {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    canBeEmpty: " + toIndentedString(canBeEmpty) + "\n" +
                "    emptyFieldText: " + toIndentedString(emptyFieldText) + "\n" +
                "    isPublic: " + toIndentedString(isPublic) + "\n" +
                "    parent: " + toIndentedString(parent) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
