/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents an activity that affects a custom field of an issue.
 */
@Schema(description = "Represents an activity that affects a custom field of an issue.")


public class CustomFieldActivityItem extends ActivityItem {
    @SerializedName("id")
    private final String customFieldActivityItemId = null;

    @SerializedName("added")
    private final Object customFieldActivityItemAdded = null;

    @SerializedName("removed")
    private final Object customFieldActivityItemRemoved = null;

    @SerializedName("target")
    private Issue customFieldActivityItemTarget = null;

    /**
     * Get customFieldActivityItemId
     *
     * @return customFieldActivityItemId
     **/
    @Schema(description = "")
    public String getCustomFieldActivityItemId() {
        return customFieldActivityItemId;
    }

    /**
     * Get customFieldActivityItemAdded
     *
     * @return customFieldActivityItemAdded
     **/
    @Schema(description = "")
    public Object getCustomFieldActivityItemAdded() {
        return customFieldActivityItemAdded;
    }

    /**
     * Get customFieldActivityItemRemoved
     *
     * @return customFieldActivityItemRemoved
     **/
    @Schema(description = "")
    public Object getCustomFieldActivityItemRemoved() {
        return customFieldActivityItemRemoved;
    }

    public CustomFieldActivityItem customFieldActivityItemTarget(Issue customFieldActivityItemTarget) {
        this.customFieldActivityItemTarget = customFieldActivityItemTarget;
        return this;
    }

    /**
     * Get customFieldActivityItemTarget
     *
     * @return customFieldActivityItemTarget
     **/
    @Schema(description = "")
    public Issue getCustomFieldActivityItemTarget() {
        return customFieldActivityItemTarget;
    }

    public void setCustomFieldActivityItemTarget(Issue customFieldActivityItemTarget) {
        this.customFieldActivityItemTarget = customFieldActivityItemTarget;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CustomFieldActivityItem customFieldActivityItem = (CustomFieldActivityItem) o;
        return Objects.equals(this.customFieldActivityItemId, customFieldActivityItem.customFieldActivityItemId) &&
                Objects.equals(this.customFieldActivityItemAdded, customFieldActivityItem.customFieldActivityItemAdded) &&
                Objects.equals(this.customFieldActivityItemRemoved, customFieldActivityItem.customFieldActivityItemRemoved) &&
                Objects.equals(this.customFieldActivityItemTarget, customFieldActivityItem.customFieldActivityItemTarget) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(customFieldActivityItemId, customFieldActivityItemAdded, customFieldActivityItemRemoved, customFieldActivityItemTarget, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class CustomFieldActivityItem {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    customFieldActivityItemId: " + toIndentedString(customFieldActivityItemId) + "\n" +
                "    customFieldActivityItemAdded: " + toIndentedString(customFieldActivityItemAdded) + "\n" +
                "    customFieldActivityItemRemoved: " + toIndentedString(customFieldActivityItemRemoved) + "\n" +
                "    customFieldActivityItemTarget: " + toIndentedString(customFieldActivityItemTarget) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
