/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * For an issue that was imported from another service, represents the reference to the issue in the external system.
 */
@Schema(description = "For an issue that was imported from another service, represents the reference to the issue in the external system.")


public class ExternalIssue {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("name")
    private final String name = null;

    @SerializedName("url")
    private final String url = null;

    @SerializedName("key")
    private final String key = null;

    @SerializedName("$type")
    private String $type = null;

    public ExternalIssue() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    /**
     * Get url
     *
     * @return url
     **/
    @Schema(description = "")
    public String getUrl() {
        return url;
    }

    /**
     * Get key
     *
     * @return key
     **/
    @Schema(description = "")
    public String getKey() {
        return key;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ExternalIssue externalIssue = (ExternalIssue) o;
        return Objects.equals(this.id, externalIssue.id) &&
                Objects.equals(this.name, externalIssue.name) &&
                Objects.equals(this.url, externalIssue.url) &&
                Objects.equals(this.key, externalIssue.key) &&
                Objects.equals(this.$type, externalIssue.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, url, key, $type);
    }


    @Override
    public String toString() {

        String sb = "class ExternalIssue {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    url: " + toIndentedString(url) + "\n" +
                "    key: " + toIndentedString(key) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
