/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents a Gogs server.
 */
@Schema(description = "Represents a Gogs server.")


public class GogsServer extends VcsHostingServer {
    @SerializedName("id")
    private final String gogsServerId = null;

    @SerializedName("url")
    private String gogsServerUrl = null;

    /**
     * Get gogsServerId
     *
     * @return gogsServerId
     **/
    @Schema(description = "")
    public String getGogsServerId() {
        return gogsServerId;
    }

    public GogsServer gogsServerUrl(String gogsServerUrl) {
        this.gogsServerUrl = gogsServerUrl;
        return this;
    }

    /**
     * Get gogsServerUrl
     *
     * @return gogsServerUrl
     **/
    @Schema(description = "")
    public String getGogsServerUrl() {
        return gogsServerUrl;
    }

    public void setGogsServerUrl(String gogsServerUrl) {
        this.gogsServerUrl = gogsServerUrl;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GogsServer gogsServer = (GogsServer) o;
        return Objects.equals(this.gogsServerId, gogsServer.gogsServerId) &&
                Objects.equals(this.gogsServerUrl, gogsServer.gogsServerUrl) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(gogsServerId, gogsServerUrl, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class GogsServer {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    gogsServerId: " + toIndentedString(gogsServerId) + "\n" +
                "    gogsServerUrl: " + toIndentedString(gogsServerUrl) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
