/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.File;
import java.util.Objects;

/**
 * IdAttachmentsBody
 */


public class IdAttachmentsBody {
    @SerializedName("files[0]")
    private File files0 = null;

    public IdAttachmentsBody files0(File files0) {
        this.files0 = files0;
        return this;
    }

    /**
     * Get files0
     *
     * @return files0
     **/
    @Schema(description = "")
    public File getFiles0() {
        return files0;
    }

    public void setFiles0(File files0) {
        this.files0 = files0;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IdAttachmentsBody idAttachmentsBody = (IdAttachmentsBody) o;
        return Objects.equals(this.files0, idAttachmentsBody.files0);
    }

    @Override
    public int hashCode() {
        return Objects.hash(Objects.hashCode(files0));
    }


    @Override
    public String toString() {

        String sb = "class IdAttachmentsBody {\n" +
                "    files0: " + toIndentedString(files0) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
