/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;
import java.util.Objects;

/**
 * IssueWorkItem
 */


public class IssueWorkItem extends BaseWorkItem {
    @SerializedName("id")
    private final String issueWorkItemId = null;

    @SerializedName("author")
    private User author = null;

    @SerializedName("creator")
    private User creator = null;

    @SerializedName("text")
    private String text = null;

    @SerializedName("textPreview")
    private final String textPreview = null;

    @SerializedName("type")
    private WorkItemType type = null;

    @SerializedName("created")
    private Long created = null;

    @SerializedName("updated")
    private Long updated = null;

    @SerializedName("duration")
    private DurationValue duration = null;

    @SerializedName("date")
    private Long date = null;

    @SerializedName("issue")
    private Issue issue = null;

    @SerializedName("attributes")
    private final List<WorkItemAttribute> attributes = null;

    /**
     * Get issueWorkItemId
     *
     * @return issueWorkItemId
     **/
    @Schema(description = "")
    public String getIssueWorkItemId() {
        return issueWorkItemId;
    }

    public IssueWorkItem author(User author) {
        this.author = author;
        return this;
    }

    /**
     * Get author
     *
     * @return author
     **/
    @Schema(description = "")
    public User getAuthor() {
        return author;
    }

    public void setAuthor(User author) {
        this.author = author;
    }

    public IssueWorkItem creator(User creator) {
        this.creator = creator;
        return this;
    }

    /**
     * Get creator
     *
     * @return creator
     **/
    @Schema(description = "")
    public User getCreator() {
        return creator;
    }

    public void setCreator(User creator) {
        this.creator = creator;
    }

    public IssueWorkItem text(String text) {
        this.text = text;
        return this;
    }

    /**
     * Get text
     *
     * @return text
     **/
    @Schema(description = "")
    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    /**
     * Get textPreview
     *
     * @return textPreview
     **/
    @Schema(description = "")
    public String getTextPreview() {
        return textPreview;
    }

    public IssueWorkItem type(WorkItemType type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @Schema(description = "")
    public WorkItemType getType() {
        return type;
    }

    public void setType(WorkItemType type) {
        this.type = type;
    }

    public IssueWorkItem created(Long created) {
        this.created = created;
        return this;
    }

    /**
     * Get created
     *
     * @return created
     **/
    @Schema(description = "")
    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created) {
        this.created = created;
    }

    public IssueWorkItem updated(Long updated) {
        this.updated = updated;
        return this;
    }

    /**
     * Get updated
     *
     * @return updated
     **/
    @Schema(description = "")
    public Long getUpdated() {
        return updated;
    }

    public void setUpdated(Long updated) {
        this.updated = updated;
    }

    public IssueWorkItem duration(DurationValue duration) {
        this.duration = duration;
        return this;
    }

    /**
     * Get duration
     *
     * @return duration
     **/
    @Schema(description = "")
    public DurationValue getDuration() {
        return duration;
    }

    public void setDuration(DurationValue duration) {
        this.duration = duration;
    }

    public IssueWorkItem date(Long date) {
        this.date = date;
        return this;
    }

    /**
     * Get date
     *
     * @return date
     **/
    @Schema(description = "")
    public Long getDate() {
        return date;
    }

    public void setDate(Long date) {
        this.date = date;
    }

    public IssueWorkItem issue(Issue issue) {
        this.issue = issue;
        return this;
    }

    /**
     * Get issue
     *
     * @return issue
     **/
    @Schema(description = "")
    public Issue getIssue() {
        return issue;
    }

    public void setIssue(Issue issue) {
        this.issue = issue;
    }

    /**
     * Get attributes
     *
     * @return attributes
     **/
    @Schema(description = "")
    public List<WorkItemAttribute> getAttributes() {
        return attributes;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IssueWorkItem issueWorkItem = (IssueWorkItem) o;
        return Objects.equals(this.issueWorkItemId, issueWorkItem.issueWorkItemId) &&
                Objects.equals(this.author, issueWorkItem.author) &&
                Objects.equals(this.creator, issueWorkItem.creator) &&
                Objects.equals(this.text, issueWorkItem.text) &&
                Objects.equals(this.textPreview, issueWorkItem.textPreview) &&
                Objects.equals(this.type, issueWorkItem.type) &&
                Objects.equals(this.created, issueWorkItem.created) &&
                Objects.equals(this.updated, issueWorkItem.updated) &&
                Objects.equals(this.duration, issueWorkItem.duration) &&
                Objects.equals(this.date, issueWorkItem.date) &&
                Objects.equals(this.issue, issueWorkItem.issue) &&
                Objects.equals(this.attributes, issueWorkItem.attributes) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(issueWorkItemId, author, creator, text, textPreview, type, created, updated, duration, date, issue, attributes, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class IssueWorkItem {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    issueWorkItemId: " + toIndentedString(issueWorkItemId) + "\n" +
                "    author: " + toIndentedString(author) + "\n" +
                "    creator: " + toIndentedString(creator) + "\n" +
                "    text: " + toIndentedString(text) + "\n" +
                "    textPreview: " + toIndentedString(textPreview) + "\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    created: " + toIndentedString(created) + "\n" +
                "    updated: " + toIndentedString(updated) + "\n" +
                "    duration: " + toIndentedString(duration) + "\n" +
                "    date: " + toIndentedString(date) + "\n" +
                "    issue: " + toIndentedString(issue) + "\n" +
                "    attributes: " + toIndentedString(attributes) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
