/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Stores information about a project where the issue belongs or previously belonged. This entity appears as part of the ProjectActivityItem object.
 */
@Schema(description = "Stores information about a project where the issue belongs or previously belonged. This entity appears as part of the ProjectActivityItem object.")


public class IssueKey {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("project")
    private Project project = null;

    @SerializedName("numberInProject")
    private final Long numberInProject = null;

    @SerializedName("$type")
    private String $type = null;

    public IssueKey() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public IssueKey project(Project project) {
        this.project = project;
        return this;
    }

    /**
     * Get project
     *
     * @return project
     **/
    @Schema(description = "")
    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    /**
     * Get numberInProject
     *
     * @return numberInProject
     **/
    @Schema(description = "")
    public Long getNumberInProject() {
        return numberInProject;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        IssueKey issueKey = (IssueKey) o;
        return Objects.equals(this.id, issueKey.id) &&
                Objects.equals(this.project, issueKey.project) &&
                Objects.equals(this.numberInProject, issueKey.numberInProject) &&
                Objects.equals(this.$type, issueKey.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, project, numberInProject, $type);
    }


    @Override
    public String toString() {

        String sb = "class IssueKey {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    project: " + toIndentedString(project) + "\n" +
                "    numberInProject: " + toIndentedString(numberInProject) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
