/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents a Jenkins integration configured for a project.
 */
@Schema(description = "Represents a Jenkins integration configured for a project.")


public class JenkinsChangesProcessor extends ChangesProcessor {
    @SerializedName("id")
    private final String jenkinsChangesProcessorId = null;

    @SerializedName("server")
    private JenkinsServer jenkinsChangesProcessorServer = null;

    /**
     * Get jenkinsChangesProcessorId
     *
     * @return jenkinsChangesProcessorId
     **/
    @Schema(description = "")
    public String getJenkinsChangesProcessorId() {
        return jenkinsChangesProcessorId;
    }

    public JenkinsChangesProcessor jenkinsChangesProcessorServer(JenkinsServer jenkinsChangesProcessorServer) {
        this.jenkinsChangesProcessorServer = jenkinsChangesProcessorServer;
        return this;
    }

    /**
     * Get jenkinsChangesProcessorServer
     *
     * @return jenkinsChangesProcessorServer
     **/
    @Schema(description = "")
    public JenkinsServer getJenkinsChangesProcessorServer() {
        return jenkinsChangesProcessorServer;
    }

    public void setJenkinsChangesProcessorServer(JenkinsServer jenkinsChangesProcessorServer) {
        this.jenkinsChangesProcessorServer = jenkinsChangesProcessorServer;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JenkinsChangesProcessor jenkinsChangesProcessor = (JenkinsChangesProcessor) o;
        return Objects.equals(this.jenkinsChangesProcessorId, jenkinsChangesProcessor.jenkinsChangesProcessorId) &&
                Objects.equals(this.jenkinsChangesProcessorServer, jenkinsChangesProcessor.jenkinsChangesProcessorServer) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(jenkinsChangesProcessorId, jenkinsChangesProcessorServer, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class JenkinsChangesProcessor {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    jenkinsChangesProcessorId: " + toIndentedString(jenkinsChangesProcessorId) + "\n" +
                "    jenkinsChangesProcessorServer: " + toIndentedString(jenkinsChangesProcessorServer) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
