/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents visibility limited to several users and/or groups.
 */
@Schema(description = "Represents visibility limited to several users and/or groups.")


public class LimitedVisibility extends Visibility {
    @SerializedName("id")
    private final String limitedVisibilityId = null;

    @SerializedName("permittedGroups")
    private List<UserGroup> permittedGroups = null;

    @SerializedName("permittedUsers")
    private List<User> permittedUsers = null;

    /**
     * Get limitedVisibilityId
     *
     * @return limitedVisibilityId
     **/
    @Schema(description = "")
    public String getLimitedVisibilityId() {
        return limitedVisibilityId;
    }

    public LimitedVisibility permittedGroups(List<UserGroup> permittedGroups) {
        this.permittedGroups = permittedGroups;
        return this;
    }

    public LimitedVisibility addPermittedGroupsItem(UserGroup permittedGroupsItem) {
        if (this.permittedGroups == null) {
            this.permittedGroups = new ArrayList<UserGroup>();
        }
        this.permittedGroups.add(permittedGroupsItem);
        return this;
    }

    /**
     * Get permittedGroups
     *
     * @return permittedGroups
     **/
    @Schema(description = "")
    public List<UserGroup> getPermittedGroups() {
        return permittedGroups;
    }

    public void setPermittedGroups(List<UserGroup> permittedGroups) {
        this.permittedGroups = permittedGroups;
    }

    public LimitedVisibility permittedUsers(List<User> permittedUsers) {
        this.permittedUsers = permittedUsers;
        return this;
    }

    public LimitedVisibility addPermittedUsersItem(User permittedUsersItem) {
        if (this.permittedUsers == null) {
            this.permittedUsers = new ArrayList<User>();
        }
        this.permittedUsers.add(permittedUsersItem);
        return this;
    }

    /**
     * Get permittedUsers
     *
     * @return permittedUsers
     **/
    @Schema(description = "")
    public List<User> getPermittedUsers() {
        return permittedUsers;
    }

    public void setPermittedUsers(List<User> permittedUsers) {
        this.permittedUsers = permittedUsers;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LimitedVisibility limitedVisibility = (LimitedVisibility) o;
        return Objects.equals(this.limitedVisibilityId, limitedVisibility.limitedVisibilityId) &&
                Objects.equals(this.permittedGroups, limitedVisibility.permittedGroups) &&
                Objects.equals(this.permittedUsers, limitedVisibility.permittedUsers) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(limitedVisibilityId, permittedGroups, permittedUsers, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class LimitedVisibility {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    limitedVisibilityId: " + toIndentedString(limitedVisibilityId) + "\n" +
                "    permittedGroups: " + toIndentedString(permittedGroups) + "\n" +
                "    permittedUsers: " + toIndentedString(permittedUsers) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
