/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents a language locale that is used in UI.
 */
@Schema(description = "Represents a language locale that is used in UI.")


public class LocaleDescriptor {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("locale")
    private final String locale = null;

    @SerializedName("language")
    private final String language = null;

    @SerializedName("community")
    private final Boolean community = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("$type")
    private String $type = null;

    public LocaleDescriptor() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    /**
     * Get locale
     *
     * @return locale
     **/
    @Schema(description = "")
    public String getLocale() {
        return locale;
    }

    /**
     * Get language
     *
     * @return language
     **/
    @Schema(description = "")
    public String getLanguage() {
        return language;
    }

    /**
     * Get community
     *
     * @return community
     **/
    @Schema(description = "")
    public Boolean isCommunity() {
        return community;
    }

    public LocaleDescriptor name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LocaleDescriptor localeDescriptor = (LocaleDescriptor) o;
        return Objects.equals(this.id, localeDescriptor.id) &&
                Objects.equals(this.locale, localeDescriptor.locale) &&
                Objects.equals(this.language, localeDescriptor.language) &&
                Objects.equals(this.community, localeDescriptor.community) &&
                Objects.equals(this.name, localeDescriptor.name) &&
                Objects.equals(this.$type, localeDescriptor.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, locale, language, community, name, $type);
    }


    @Override
    public String toString() {

        String sb = "class LocaleDescriptor {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    locale: " + toIndentedString(locale) + "\n" +
                "    language: " + toIndentedString(language) + "\n" +
                "    community: " + toIndentedString(community) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
