/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents field value that can be localized.
 */
@Schema(description = "Represents field value that can be localized.")


public class LocalizableBundleElement extends BundleElement {
    @SerializedName("id")
    private final String localizableBundleElementId = null;

    @SerializedName("localizedName")
    private String localizedName = null;

    /**
     * Get localizableBundleElementId
     *
     * @return localizableBundleElementId
     **/
    @Schema(description = "")
    public String getLocalizableBundleElementId() {
        return localizableBundleElementId;
    }

    public LocalizableBundleElement localizedName(String localizedName) {
        this.localizedName = localizedName;
        return this;
    }

    /**
     * Get localizedName
     *
     * @return localizedName
     **/
    @Schema(description = "")
    public String getLocalizedName() {
        return localizedName;
    }

    public void setLocalizedName(String localizedName) {
        this.localizedName = localizedName;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LocalizableBundleElement localizableBundleElement = (LocalizableBundleElement) o;
        return Objects.equals(this.localizableBundleElementId, localizableBundleElement.localizableBundleElementId) &&
                Objects.equals(this.localizedName, localizableBundleElement.localizedName) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(localizableBundleElementId, localizedName, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class LocalizableBundleElement {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    localizableBundleElementId: " + toIndentedString(localizableBundleElementId) + "\n" +
                "    localizedName: " + toIndentedString(localizedName) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
