/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OwnedBundle
 */


public class OwnedBundle extends BaseBundle {
    @SerializedName("id")
    private final String ownedBundleId = null;

    @SerializedName("values")
    private List<OwnedBundleElement> ownedBundleValues = null;

    /**
     * Get ownedBundleId
     *
     * @return ownedBundleId
     **/
    @Schema(description = "")
    public String getOwnedBundleId() {
        return ownedBundleId;
    }

    public OwnedBundle ownedBundleValues(List<OwnedBundleElement> ownedBundleValues) {
        this.ownedBundleValues = ownedBundleValues;
        return this;
    }

    public OwnedBundle addOwnedBundleValuesItem(OwnedBundleElement ownedBundleValuesItem) {
        if (this.ownedBundleValues == null) {
            this.ownedBundleValues = new ArrayList<OwnedBundleElement>();
        }
        this.ownedBundleValues.add(ownedBundleValuesItem);
        return this;
    }

    /**
     * Get ownedBundleValues
     *
     * @return ownedBundleValues
     **/
    @Schema(description = "")
    public List<OwnedBundleElement> getOwnedBundleValues() {
        return ownedBundleValues;
    }

    public void setOwnedBundleValues(List<OwnedBundleElement> ownedBundleValues) {
        this.ownedBundleValues = ownedBundleValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OwnedBundle ownedBundle = (OwnedBundle) o;
        return Objects.equals(this.ownedBundleId, ownedBundle.ownedBundleId) &&
                Objects.equals(this.ownedBundleValues, ownedBundle.ownedBundleValues) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(ownedBundleId, ownedBundleValues, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class OwnedBundle {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    ownedBundleId: " + toIndentedString(ownedBundleId) + "\n" +
                "    ownedBundleValues: " + toIndentedString(ownedBundleValues) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
