/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents project settings for an owned field.
 */
@Schema(description = "Represents project settings for an owned field.")


public class OwnedProjectCustomField extends BundleProjectCustomField {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("bundle")
    private OwnedBundle bundle = null;

    @SerializedName("defaultValues")
    private List<OwnedBundleElement> defaultValues = null;

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public OwnedProjectCustomField bundle(OwnedBundle bundle) {
        this.bundle = bundle;
        return this;
    }

    /**
     * Get bundle
     *
     * @return bundle
     **/
    @Schema(description = "")
    public OwnedBundle getBundle() {
        return bundle;
    }

    public void setBundle(OwnedBundle bundle) {
        this.bundle = bundle;
    }

    public OwnedProjectCustomField defaultValues(List<OwnedBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
        return this;
    }

    public OwnedProjectCustomField addDefaultValuesItem(OwnedBundleElement defaultValuesItem) {
        if (this.defaultValues == null) {
            this.defaultValues = new ArrayList<OwnedBundleElement>();
        }
        this.defaultValues.add(defaultValuesItem);
        return this;
    }

    /**
     * Get defaultValues
     *
     * @return defaultValues
     **/
    @Schema(description = "")
    public List<OwnedBundleElement> getDefaultValues() {
        return defaultValues;
    }

    public void setDefaultValues(List<OwnedBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OwnedProjectCustomField ownedProjectCustomField = (OwnedProjectCustomField) o;
        return Objects.equals(this.id, ownedProjectCustomField.id) &&
                Objects.equals(this.bundle, ownedProjectCustomField.bundle) &&
                Objects.equals(this.defaultValues, ownedProjectCustomField.defaultValues) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, bundle, defaultValues, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class OwnedProjectCustomField {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    bundle: " + toIndentedString(bundle) + "\n" +
                "    defaultValues: " + toIndentedString(defaultValues) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
