/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents the command that was parsed from the provided query.
 */
@Schema(description = "Represents the command that was parsed from the provided query.")


public class ParsedCommand {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("description")
    private final String description = null;

    @SerializedName("error")
    private final Boolean error = null;

    @SerializedName("delete")
    private final Boolean delete = null;

    @SerializedName("$type")
    private String $type = null;

    public ParsedCommand() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    /**
     * Get description
     *
     * @return description
     **/
    @Schema(description = "")
    public String getDescription() {
        return description;
    }

    /**
     * Get error
     *
     * @return error
     **/
    @Schema(description = "")
    public Boolean isError() {
        return error;
    }

    /**
     * Get delete
     *
     * @return delete
     **/
    @Schema(description = "")
    public Boolean isDelete() {
        return delete;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ParsedCommand parsedCommand = (ParsedCommand) o;
        return Objects.equals(this.id, parsedCommand.id) &&
                Objects.equals(this.description, parsedCommand.description) &&
                Objects.equals(this.error, parsedCommand.error) &&
                Objects.equals(this.delete, parsedCommand.delete) &&
                Objects.equals(this.$type, parsedCommand.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, description, error, delete, $type);
    }


    @Override
    public String toString() {

        String sb = "class ParsedCommand {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    description: " + toIndentedString(description) + "\n" +
                "    error: " + toIndentedString(error) + "\n" +
                "    delete: " + toIndentedString(delete) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
