/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents a predefined field of the issue. Predefined fields are always present in an issue and             |cannot be customized in a project. For example, &#x60;project&#x60;, &#x60;created&#x60;,             |&#x60;updated&#x60;, &#x60;tags&#x60;, and so on.
 */
@Schema(description = "Represents a predefined field of the issue. Predefined fields are always present in an issue and             |cannot be customized in a project. For example, `project`, `created`,             |`updated`, `tags`, and so on.")


public class PredefinedFilterField extends FilterField {
    @SerializedName("id")
    private final String predefinedFilterFieldId = null;

    /**
     * Get predefinedFilterFieldId
     *
     * @return predefinedFilterFieldId
     **/
    @Schema(description = "")
    public String getPredefinedFilterFieldId() {
        return predefinedFilterFieldId;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PredefinedFilterField predefinedFilterField = (PredefinedFilterField) o;
        return Objects.equals(this.predefinedFilterFieldId, predefinedFilterField.predefinedFilterFieldId) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(predefinedFilterFieldId, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class PredefinedFilterField {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    predefinedFilterFieldId: " + toIndentedString(predefinedFilterFieldId) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
