/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents the change in the project attribute on an issue.
 */
@Schema(description = "Represents the change in the project attribute on an issue.")


public class ProjectActivityItem extends SingleValueActivityItem {
    @SerializedName("id")
    private final String projectActivityItemId = null;

    @SerializedName("added")
    private IssueKey projectActivityItemAdded = null;

    @SerializedName("removed")
    private IssueKey projectActivityItemRemoved = null;

    @SerializedName("target")
    private Issue projectActivityItemTarget = null;

    /**
     * Get projectActivityItemId
     *
     * @return projectActivityItemId
     **/
    @Schema(description = "")
    public String getProjectActivityItemId() {
        return projectActivityItemId;
    }

    public ProjectActivityItem projectActivityItemAdded(IssueKey projectActivityItemAdded) {
        this.projectActivityItemAdded = projectActivityItemAdded;
        return this;
    }

    /**
     * Get projectActivityItemAdded
     *
     * @return projectActivityItemAdded
     **/
    @Schema(description = "")
    public IssueKey getProjectActivityItemAdded() {
        return projectActivityItemAdded;
    }

    public void setProjectActivityItemAdded(IssueKey projectActivityItemAdded) {
        this.projectActivityItemAdded = projectActivityItemAdded;
    }

    public ProjectActivityItem projectActivityItemRemoved(IssueKey projectActivityItemRemoved) {
        this.projectActivityItemRemoved = projectActivityItemRemoved;
        return this;
    }

    /**
     * Get projectActivityItemRemoved
     *
     * @return projectActivityItemRemoved
     **/
    @Schema(description = "")
    public IssueKey getProjectActivityItemRemoved() {
        return projectActivityItemRemoved;
    }

    public void setProjectActivityItemRemoved(IssueKey projectActivityItemRemoved) {
        this.projectActivityItemRemoved = projectActivityItemRemoved;
    }

    public ProjectActivityItem projectActivityItemTarget(Issue projectActivityItemTarget) {
        this.projectActivityItemTarget = projectActivityItemTarget;
        return this;
    }

    /**
     * Get projectActivityItemTarget
     *
     * @return projectActivityItemTarget
     **/
    @Schema(description = "")
    public Issue getProjectActivityItemTarget() {
        return projectActivityItemTarget;
    }

    public void setProjectActivityItemTarget(Issue projectActivityItemTarget) {
        this.projectActivityItemTarget = projectActivityItemTarget;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProjectActivityItem projectActivityItem = (ProjectActivityItem) o;
        return Objects.equals(this.projectActivityItemId, projectActivityItem.projectActivityItemId) &&
                Objects.equals(this.projectActivityItemAdded, projectActivityItem.projectActivityItemAdded) &&
                Objects.equals(this.projectActivityItemRemoved, projectActivityItem.projectActivityItemRemoved) &&
                Objects.equals(this.projectActivityItemTarget, projectActivityItem.projectActivityItemTarget) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(projectActivityItemId, projectActivityItemAdded, projectActivityItemRemoved, projectActivityItemTarget, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class ProjectActivityItem {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    projectActivityItemId: " + toIndentedString(projectActivityItemId) + "\n" +
                "    projectActivityItemAdded: " + toIndentedString(projectActivityItemAdded) + "\n" +
                "    projectActivityItemRemoved: " + toIndentedString(projectActivityItemRemoved) + "\n" +
                "    projectActivityItemTarget: " + toIndentedString(projectActivityItemTarget) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
