/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;
import java.util.Objects;

/**
 * SavedQuery
 */


public class SavedQuery extends WatchFolder {
    @SerializedName("query")
    protected String query = null;

    @SerializedName("issues")
    protected final List<Issue> issues = null;


    /**
     * Get savedQueryId
     *
     * @return savedQueryId
     **/
    @Schema(description = "")
    public String getSavedQueryId() {
        return id;
    }

    public SavedQuery query(String query) {
        this.query = query;
        return this;
    }

    /**
     * Get query
     *
     * @return query
     **/
    @Schema(description = "")
    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

    /**
     * Get issues
     *
     * @return issues
     **/
    @Schema(description = "")
    public List<Issue> getIssues() {
        return issues;
    }

    public SavedQuery savedQueryVisibleFor(UserGroup savedQueryVisibleFor) {
        this.visibleFor = savedQueryVisibleFor;
        return this;
    }

    /**
     * Get savedQueryVisibleFor
     *
     * @return savedQueryVisibleFor
     **/
    @Schema(description = "")
    public UserGroup getSavedQueryVisibleFor() {
        return visibleFor;
    }

    public void setSavedQueryVisibleFor(UserGroup savedQueryVisibleFor) {
        this.visibleFor = savedQueryVisibleFor;
    }

    public SavedQuery savedQueryUpdateableBy(UserGroup savedQueryUpdateableBy) {
        this.updateableBy = savedQueryUpdateableBy;
        return this;
    }

    /**
     * Get savedQueryUpdateableBy
     *
     * @return savedQueryUpdateableBy
     **/
    @Schema(description = "")
    public UserGroup getSavedQueryUpdateableBy() {
        return updateableBy;
    }

    public void setSavedQueryUpdateableBy(UserGroup savedQueryUpdateableBy) {
        this.updateableBy = savedQueryUpdateableBy;
    }

    public SavedQuery savedQueryReadSharingSettings(WatchFolderSharingSettings savedQueryReadSharingSettings) {
        this.readSharingSettings = savedQueryReadSharingSettings;
        return this;
    }

    /**
     * Get savedQueryReadSharingSettings
     *
     * @return savedQueryReadSharingSettings
     **/
    @Schema(description = "")
    public WatchFolderSharingSettings getSavedQueryReadSharingSettings() {
        return readSharingSettings;
    }

    public void setSavedQueryReadSharingSettings(WatchFolderSharingSettings savedQueryReadSharingSettings) {
        this.readSharingSettings = savedQueryReadSharingSettings;
    }

    public SavedQuery savedQueryUpdateSharingSettings(WatchFolderSharingSettings savedQueryUpdateSharingSettings) {
        this.updateSharingSettings = savedQueryUpdateSharingSettings;
        return this;
    }

    /**
     * Get savedQueryUpdateSharingSettings
     *
     * @return savedQueryUpdateSharingSettings
     **/
    @Schema(description = "")
    public WatchFolderSharingSettings getSavedQueryUpdateSharingSettings() {
        return updateSharingSettings;
    }

    public void setSavedQueryUpdateSharingSettings(WatchFolderSharingSettings savedQueryUpdateSharingSettings) {
        this.updateSharingSettings = savedQueryUpdateSharingSettings;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SavedQuery savedQuery = (SavedQuery) o;
        return Objects.equals(this.id, savedQuery.id) &&
                Objects.equals(this.query, savedQuery.query) &&
                Objects.equals(this.issues, savedQuery.issues) &&
                Objects.equals(this.visibleFor, savedQuery.visibleFor) &&
                Objects.equals(this.updateableBy, savedQuery.updateableBy) &&
                Objects.equals(this.readSharingSettings, savedQuery.readSharingSettings) &&
                Objects.equals(this.updateSharingSettings, savedQuery.updateSharingSettings) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, query, issues, visibleFor, updateableBy, readSharingSettings, updateSharingSettings, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class SavedQuery {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    savedQueryId: " + toIndentedString(id) + "\n" +
                "    query: " + toIndentedString(query) + "\n" +
                "    issues: " + toIndentedString(issues) + "\n" +
                "    savedQueryVisibleFor: " + toIndentedString(visibleFor) + "\n" +
                "    savedQueryUpdateableBy: " + toIndentedString(updateableBy) + "\n" +
                "    savedQueryReadSharingSettings: " + toIndentedString(readSharingSettings) + "\n" +
                "    savedQueryUpdateSharingSettings: " + toIndentedString(updateSharingSettings) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
