/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents project settings for the fields of the following types: &#x60;integer&#x60;, &#x60;float&#x60;, &#x60;date&#x60;, &#x60;date and time&#x60;, &#x60;string&#x60;.
 */
@Schema(description = "Represents project settings for the fields of the following types: `integer`, `float`, `date`, `date and time`, `string`.")


public class SimpleProjectCustomField extends ProjectCustomField {
    @SerializedName("id")
    private final String simpleProjectCustomFieldId = null;

    /**
     * Get simpleProjectCustomFieldId
     *
     * @return simpleProjectCustomFieldId
     **/
    @Schema(description = "")
    public String getSimpleProjectCustomFieldId() {
        return simpleProjectCustomFieldId;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SimpleProjectCustomField simpleProjectCustomField = (SimpleProjectCustomField) o;
        return Objects.equals(this.simpleProjectCustomFieldId, simpleProjectCustomField.simpleProjectCustomFieldId) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(simpleProjectCustomFieldId, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class SimpleProjectCustomField {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    simpleProjectCustomFieldId: " + toIndentedString(simpleProjectCustomFieldId) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
