/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents project settings for a state field.
 */
@Schema(description = "Represents project settings for a state field.")


public class StateProjectCustomField extends BundleProjectCustomField {
    @SerializedName("id")
    private final String stateProjectCustomFieldId = null;

    @SerializedName("bundle")
    private StateBundle bundle = null;

    @SerializedName("defaultValues")
    private List<StateBundleElement> defaultValues = null;

    /**
     * Get stateProjectCustomFieldId
     *
     * @return stateProjectCustomFieldId
     **/
    @Schema(description = "")
    public String getStateProjectCustomFieldId() {
        return stateProjectCustomFieldId;
    }

    public StateProjectCustomField bundle(StateBundle bundle) {
        this.bundle = bundle;
        return this;
    }

    /**
     * Get bundle
     *
     * @return bundle
     **/
    @Schema(description = "")
    public StateBundle getBundle() {
        return bundle;
    }

    public void setBundle(StateBundle bundle) {
        this.bundle = bundle;
    }

    public StateProjectCustomField defaultValues(List<StateBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
        return this;
    }

    public StateProjectCustomField addDefaultValuesItem(StateBundleElement defaultValuesItem) {
        if (this.defaultValues == null) {
            this.defaultValues = new ArrayList<StateBundleElement>();
        }
        this.defaultValues.add(defaultValuesItem);
        return this;
    }

    /**
     * Get defaultValues
     *
     * @return defaultValues
     **/
    @Schema(description = "")
    public List<StateBundleElement> getDefaultValues() {
        return defaultValues;
    }

    public void setDefaultValues(List<StateBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StateProjectCustomField stateProjectCustomField = (StateProjectCustomField) o;
        return Objects.equals(this.stateProjectCustomFieldId, stateProjectCustomField.stateProjectCustomFieldId) &&
                Objects.equals(this.bundle, stateProjectCustomField.bundle) &&
                Objects.equals(this.defaultValues, stateProjectCustomField.defaultValues) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(stateProjectCustomFieldId, bundle, defaultValues, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class StateProjectCustomField {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    stateProjectCustomFieldId: " + toIndentedString(stateProjectCustomFieldId) + "\n" +
                "    bundle: " + toIndentedString(bundle) + "\n" +
                "    defaultValues: " + toIndentedString(defaultValues) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
