/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents a single swimlane in case of AttributeBasedSwimlaneSettings.
 */
@Schema(description = "Represents a single swimlane in case of AttributeBasedSwimlaneSettings.")


public class SwimlaneEntityAttributeValue extends DatabaseAttributeValue {
    @SerializedName("id")
    private final String swimlaneEntityAttributeValueId = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("isResolved")
    private final Boolean isResolved = null;

    /**
     * Get swimlaneEntityAttributeValueId
     *
     * @return swimlaneEntityAttributeValueId
     **/
    @Schema(description = "")
    public String getSwimlaneEntityAttributeValueId() {
        return swimlaneEntityAttributeValueId;
    }

    public SwimlaneEntityAttributeValue name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Get isResolved
     *
     * @return isResolved
     **/
    @Schema(description = "")
    public Boolean isIsResolved() {
        return isResolved;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SwimlaneEntityAttributeValue swimlaneEntityAttributeValue = (SwimlaneEntityAttributeValue) o;
        return Objects.equals(this.swimlaneEntityAttributeValueId, swimlaneEntityAttributeValue.swimlaneEntityAttributeValueId) &&
                Objects.equals(this.name, swimlaneEntityAttributeValue.name) &&
                Objects.equals(this.isResolved, swimlaneEntityAttributeValue.isResolved) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(swimlaneEntityAttributeValueId, name, isResolved, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class SwimlaneEntityAttributeValue {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    swimlaneEntityAttributeValueId: " + toIndentedString(swimlaneEntityAttributeValueId) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    isResolved: " + toIndentedString(isResolved) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
