/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents a TeamCity server.
 */
@Schema(description = "Represents a TeamCity server.")


public class TeamcityServer extends VcsServer {
    @SerializedName("id")
    private final String teamcityServerId = null;

    @SerializedName("url")
    private String teamcityServerUrl = null;

    /**
     * Get teamcityServerId
     *
     * @return teamcityServerId
     **/
    @Schema(description = "")
    public String getTeamcityServerId() {
        return teamcityServerId;
    }

    public TeamcityServer teamcityServerUrl(String teamcityServerUrl) {
        this.teamcityServerUrl = teamcityServerUrl;
        return this;
    }

    /**
     * Get teamcityServerUrl
     *
     * @return teamcityServerUrl
     **/
    @Schema(description = "")
    public String getTeamcityServerUrl() {
        return teamcityServerUrl;
    }

    public void setTeamcityServerUrl(String teamcityServerUrl) {
        this.teamcityServerUrl = teamcityServerUrl;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TeamcityServer teamcityServer = (TeamcityServer) o;
        return Objects.equals(this.teamcityServerId, teamcityServer.teamcityServerId) &&
                Objects.equals(this.teamcityServerUrl, teamcityServer.teamcityServerUrl) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(teamcityServerId, teamcityServerUrl, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class TeamcityServer {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    teamcityServerId: " + toIndentedString(teamcityServerId) + "\n" +
                "    teamcityServerUrl: " + toIndentedString(teamcityServerUrl) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
