/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import java.util.Objects;
import java.util.Arrays;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.jetbrains.youtrack.CustomFieldActivityItem;
import com.jetbrains.youtrack.Issue;
import io.swagger.v3.oas.annotations.media.Schema;

import java.io.IOException;

/**
 * Represents an activity that affects a custom field of the &#x60;text&#x60; type of an issue.
 */
@Schema(description = "Represents an activity that affects a custom field of the `text` type of an issue.")


public class TextCustomFieldActivityItem extends CustomFieldActivityItem {
    @SerializedName("id")
    private final String textCustomFieldActivityItemId = null;

    @SerializedName("added")
    private final String textCustomFieldActivityItemAdded = null;

    @SerializedName("markup")
    private final String markup = null;

    @SerializedName("removed")
    private final String textCustomFieldActivityItemRemoved = null;

    @SerializedName("target")
    private Issue textCustomFieldActivityItemTarget = null;

    /**
     * Get textCustomFieldActivityItemId
     *
     * @return textCustomFieldActivityItemId
     **/
    @Schema(description = "")
    public String getTextCustomFieldActivityItemId() {
        return textCustomFieldActivityItemId;
    }

    /**
     * Get textCustomFieldActivityItemAdded
     *
     * @return textCustomFieldActivityItemAdded
     **/
    @Schema(description = "")
    public String getTextCustomFieldActivityItemAdded() {
        return textCustomFieldActivityItemAdded;
    }

    /**
     * Get markup
     *
     * @return markup
     **/
    @Schema(description = "")
    public String getMarkup() {
        return markup;
    }

    /**
     * Get textCustomFieldActivityItemRemoved
     *
     * @return textCustomFieldActivityItemRemoved
     **/
    @Schema(description = "")
    public String getTextCustomFieldActivityItemRemoved() {
        return textCustomFieldActivityItemRemoved;
    }

    public TextCustomFieldActivityItem textCustomFieldActivityItemTarget(Issue textCustomFieldActivityItemTarget) {
        this.textCustomFieldActivityItemTarget = textCustomFieldActivityItemTarget;
        return this;
    }

    /**
     * Get textCustomFieldActivityItemTarget
     *
     * @return textCustomFieldActivityItemTarget
     **/
    @Schema(description = "")
    public Issue getTextCustomFieldActivityItemTarget() {
        return textCustomFieldActivityItemTarget;
    }

    public void setTextCustomFieldActivityItemTarget(Issue textCustomFieldActivityItemTarget) {
        this.textCustomFieldActivityItemTarget = textCustomFieldActivityItemTarget;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TextCustomFieldActivityItem textCustomFieldActivityItem = (TextCustomFieldActivityItem) o;
        return Objects.equals(this.textCustomFieldActivityItemId, textCustomFieldActivityItem.textCustomFieldActivityItemId) &&
                Objects.equals(this.textCustomFieldActivityItemAdded, textCustomFieldActivityItem.textCustomFieldActivityItemAdded) &&
                Objects.equals(this.markup, textCustomFieldActivityItem.markup) &&
                Objects.equals(this.textCustomFieldActivityItemRemoved, textCustomFieldActivityItem.textCustomFieldActivityItemRemoved) &&
                Objects.equals(this.textCustomFieldActivityItemTarget, textCustomFieldActivityItem.textCustomFieldActivityItemTarget) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(textCustomFieldActivityItemId, textCustomFieldActivityItemAdded, markup, textCustomFieldActivityItemRemoved, textCustomFieldActivityItemTarget, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class TextCustomFieldActivityItem {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    textCustomFieldActivityItemId: " + toIndentedString(textCustomFieldActivityItemId) + "\n" +
                "    textCustomFieldActivityItemAdded: " + toIndentedString(textCustomFieldActivityItemAdded) + "\n" +
                "    markup: " + toIndentedString(markup) + "\n" +
                "    textCustomFieldActivityItemRemoved: " + toIndentedString(textCustomFieldActivityItemRemoved) + "\n" +
                "    textCustomFieldActivityItemTarget: " + toIndentedString(textCustomFieldActivityItemTarget) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
