/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents the issue custom field of the &#x60;text&#x60; type.
 */
@Schema(description = "Represents the issue custom field of the `text` type.")


public class TextIssueCustomField extends IssueCustomField {
    @SerializedName("id")
    private final String textIssueCustomFieldId = null;

    @SerializedName("value")
    private TextFieldValue textIssueCustomFieldValue = null;

    /**
     * Get textIssueCustomFieldId
     *
     * @return textIssueCustomFieldId
     **/
    @Schema(description = "")
    public String getTextIssueCustomFieldId() {
        return textIssueCustomFieldId;
    }

    public TextIssueCustomField textIssueCustomFieldValue(TextFieldValue textIssueCustomFieldValue) {
        this.textIssueCustomFieldValue = textIssueCustomFieldValue;
        return this;
    }

    /**
     * Get textIssueCustomFieldValue
     *
     * @return textIssueCustomFieldValue
     **/
    @Schema(description = "")
    public TextFieldValue getTextIssueCustomFieldValue() {
        return textIssueCustomFieldValue;
    }

    public void setTextIssueCustomFieldValue(TextFieldValue textIssueCustomFieldValue) {
        this.textIssueCustomFieldValue = textIssueCustomFieldValue;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TextIssueCustomField textIssueCustomField = (TextIssueCustomField) o;
        return Objects.equals(this.textIssueCustomFieldId, textIssueCustomField.textIssueCustomFieldId) &&
                Objects.equals(this.textIssueCustomFieldValue, textIssueCustomField.textIssueCustomFieldValue) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(textIssueCustomFieldId, textIssueCustomFieldValue, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class TextIssueCustomField {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    textIssueCustomFieldId: " + toIndentedString(textIssueCustomFieldId) + "\n" +
                "    textIssueCustomFieldValue: " + toIndentedString(textIssueCustomFieldValue) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
