/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.List;
import java.util.Objects;

/**
 * Represents an update in the list of VCS changes of an issue.
 */
@Schema(description = "Represents an update in the list of VCS changes of an issue.")


public class VcsChangeActivityItem extends CreatedDeletedActivityItem {
    @SerializedName("id")
    private final String vcsChangeActivityItemId = null;

    @SerializedName("removed")
    private final List<VcsChange> vcsChangeActivityItemRemoved = null;

    @SerializedName("added")
    private final List<VcsChange> vcsChangeActivityItemAdded = null;

    @SerializedName("author")
    private User vcsChangeActivityItemAuthor = null;

    /**
     * Get vcsChangeActivityItemId
     *
     * @return vcsChangeActivityItemId
     **/
    @Schema(description = "")
    public String getVcsChangeActivityItemId() {
        return vcsChangeActivityItemId;
    }

    /**
     * Get vcsChangeActivityItemRemoved
     *
     * @return vcsChangeActivityItemRemoved
     **/
    @Schema(description = "")
    public List<VcsChange> getVcsChangeActivityItemRemoved() {
        return vcsChangeActivityItemRemoved;
    }

    /**
     * Get vcsChangeActivityItemAdded
     *
     * @return vcsChangeActivityItemAdded
     **/
    @Schema(description = "")
    public List<VcsChange> getVcsChangeActivityItemAdded() {
        return vcsChangeActivityItemAdded;
    }

    public VcsChangeActivityItem vcsChangeActivityItemAuthor(User vcsChangeActivityItemAuthor) {
        this.vcsChangeActivityItemAuthor = vcsChangeActivityItemAuthor;
        return this;
    }

    /**
     * Get vcsChangeActivityItemAuthor
     *
     * @return vcsChangeActivityItemAuthor
     **/
    @Schema(description = "")
    public User getVcsChangeActivityItemAuthor() {
        return vcsChangeActivityItemAuthor;
    }

    public void setVcsChangeActivityItemAuthor(User vcsChangeActivityItemAuthor) {
        this.vcsChangeActivityItemAuthor = vcsChangeActivityItemAuthor;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VcsChangeActivityItem vcsChangeActivityItem = (VcsChangeActivityItem) o;
        return Objects.equals(this.vcsChangeActivityItemId, vcsChangeActivityItem.vcsChangeActivityItemId) &&
                Objects.equals(this.vcsChangeActivityItemRemoved, vcsChangeActivityItem.vcsChangeActivityItemRemoved) &&
                Objects.equals(this.vcsChangeActivityItemAdded, vcsChangeActivityItem.vcsChangeActivityItemAdded) &&
                Objects.equals(this.vcsChangeActivityItemAuthor, vcsChangeActivityItem.vcsChangeActivityItemAuthor) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(vcsChangeActivityItemId, vcsChangeActivityItemRemoved, vcsChangeActivityItemAdded, vcsChangeActivityItemAuthor, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class VcsChangeActivityItem {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    vcsChangeActivityItemId: " + toIndentedString(vcsChangeActivityItemId) + "\n" +
                "    vcsChangeActivityItemRemoved: " + toIndentedString(vcsChangeActivityItemRemoved) + "\n" +
                "    vcsChangeActivityItemAdded: " + toIndentedString(vcsChangeActivityItemAdded) + "\n" +
                "    vcsChangeActivityItemAuthor: " + toIndentedString(vcsChangeActivityItemAuthor) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
