/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Default settings for the version-type field.
 */
@Schema(description = "Default settings for the version-type field.")


public class VersionBundleCustomFieldDefaults extends BundleCustomFieldDefaults {
    @SerializedName("id")
    private final String versionBundleCustomFieldDefaultsId = null;

    @SerializedName("bundle")
    private VersionBundle bundle = null;

    @SerializedName("defaultValues")
    private List<VersionBundleElement> defaultValues = null;

    /**
     * Get versionBundleCustomFieldDefaultsId
     *
     * @return versionBundleCustomFieldDefaultsId
     **/
    @Schema(description = "")
    public String getVersionBundleCustomFieldDefaultsId() {
        return versionBundleCustomFieldDefaultsId;
    }

    public VersionBundleCustomFieldDefaults bundle(VersionBundle bundle) {
        this.bundle = bundle;
        return this;
    }

    /**
     * Get bundle
     *
     * @return bundle
     **/
    @Schema(description = "")
    public VersionBundle getBundle() {
        return bundle;
    }

    public void setBundle(VersionBundle bundle) {
        this.bundle = bundle;
    }

    public VersionBundleCustomFieldDefaults defaultValues(List<VersionBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
        return this;
    }

    public VersionBundleCustomFieldDefaults addDefaultValuesItem(VersionBundleElement defaultValuesItem) {
        if (this.defaultValues == null) {
            this.defaultValues = new ArrayList<VersionBundleElement>();
        }
        this.defaultValues.add(defaultValuesItem);
        return this;
    }

    /**
     * Get defaultValues
     *
     * @return defaultValues
     **/
    @Schema(description = "")
    public List<VersionBundleElement> getDefaultValues() {
        return defaultValues;
    }

    public void setDefaultValues(List<VersionBundleElement> defaultValues) {
        this.defaultValues = defaultValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VersionBundleCustomFieldDefaults versionBundleCustomFieldDefaults = (VersionBundleCustomFieldDefaults) o;
        return Objects.equals(this.versionBundleCustomFieldDefaultsId, versionBundleCustomFieldDefaults.versionBundleCustomFieldDefaultsId) &&
                Objects.equals(this.bundle, versionBundleCustomFieldDefaults.bundle) &&
                Objects.equals(this.defaultValues, versionBundleCustomFieldDefaults.defaultValues) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(versionBundleCustomFieldDefaultsId, bundle, defaultValues, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class VersionBundleCustomFieldDefaults {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    versionBundleCustomFieldDefaultsId: " + toIndentedString(versionBundleCustomFieldDefaultsId) + "\n" +
                "    bundle: " + toIndentedString(bundle) + "\n" +
                "    defaultValues: " + toIndentedString(defaultValues) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
