/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * VersionBundle
 */


public class VersionBundle extends BaseBundle {
    @SerializedName("id")
    private final String versionBundleId = null;

    @SerializedName("values")
    private List<VersionBundleElement> versionBundleValues = null;

    /**
     * Get versionBundleId
     *
     * @return versionBundleId
     **/
    @Schema(description = "")
    public String getVersionBundleId() {
        return versionBundleId;
    }

    public VersionBundle versionBundleValues(List<VersionBundleElement> versionBundleValues) {
        this.versionBundleValues = versionBundleValues;
        return this;
    }

    public VersionBundle addVersionBundleValuesItem(VersionBundleElement versionBundleValuesItem) {
        if (this.versionBundleValues == null) {
            this.versionBundleValues = new ArrayList<VersionBundleElement>();
        }
        this.versionBundleValues.add(versionBundleValuesItem);
        return this;
    }

    /**
     * Get versionBundleValues
     *
     * @return versionBundleValues
     **/
    @Schema(description = "")
    public List<VersionBundleElement> getVersionBundleValues() {
        return versionBundleValues;
    }

    public void setVersionBundleValues(List<VersionBundleElement> versionBundleValues) {
        this.versionBundleValues = versionBundleValues;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VersionBundle versionBundle = (VersionBundle) o;
        return Objects.equals(this.versionBundleId, versionBundle.versionBundleId) &&
                Objects.equals(this.versionBundleValues, versionBundle.versionBundleValues) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(versionBundleId, versionBundleValues, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class VersionBundle {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    versionBundleId: " + toIndentedString(versionBundleId) + "\n" +
                "    versionBundleValues: " + toIndentedString(versionBundleValues) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
