/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Represents WIP limits for particular column. If they are not satisfied, the column will be highlighted in UI.
 */
@Schema(description = "Represents WIP limits for particular column. If they are not satisfied, the column will be highlighted in UI.")


public class WIPLimit {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("max")
    private Integer max = null;

    @SerializedName("min")
    private Integer min = null;

    @SerializedName("column")
    private AgileColumn column = null;

    @SerializedName("$type")
    private String $type = null;

    public WIPLimit() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public WIPLimit max(Integer max) {
        this.max = max;
        return this;
    }

    /**
     * Get max
     *
     * @return max
     **/
    @Schema(description = "")
    public Integer getMax() {
        return max;
    }

    public void setMax(Integer max) {
        this.max = max;
    }

    public WIPLimit min(Integer min) {
        this.min = min;
        return this;
    }

    /**
     * Get min
     *
     * @return min
     **/
    @Schema(description = "")
    public Integer getMin() {
        return min;
    }

    public void setMin(Integer min) {
        this.min = min;
    }

    public WIPLimit column(AgileColumn column) {
        this.column = column;
        return this;
    }

    /**
     * Get column
     *
     * @return column
     **/
    @Schema(description = "")
    public AgileColumn getColumn() {
        return column;
    }

    public void setColumn(AgileColumn column) {
        this.column = column;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WIPLimit wiPLimit = (WIPLimit) o;
        return Objects.equals(this.id, wiPLimit.id) &&
                Objects.equals(this.max, wiPLimit.max) &&
                Objects.equals(this.min, wiPLimit.min) &&
                Objects.equals(this.column, wiPLimit.column) &&
                Objects.equals(this.$type, wiPLimit.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, max, min, column, $type);
    }


    @Override
    public String toString() {

        String sb = "class WIPLimit {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    max: " + toIndentedString(max) + "\n" +
                "    min: " + toIndentedString(min) + "\n" +
                "    column: " + toIndentedString(column) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
