/*
 * YouTrack REST API
 * YouTrack issue tracking and project management system
 *
 * OpenAPI spec version: 2024.2
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.youtrack;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * WorkItemType
 */


public class WorkItemType {
    @SerializedName("id")
    private final String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("autoAttached")
    private Boolean autoAttached = null;

    @SerializedName("$type")
    private String $type = null;

    public WorkItemType() {
        this.$type = this.getClass().getSimpleName();
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public WorkItemType name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public WorkItemType autoAttached(Boolean autoAttached) {
        this.autoAttached = autoAttached;
        return this;
    }

    /**
     * Get autoAttached
     *
     * @return autoAttached
     **/
    @Schema(description = "")
    public Boolean isAutoAttached() {
        return autoAttached;
    }

    public void setAutoAttached(Boolean autoAttached) {
        this.autoAttached = autoAttached;
    }

    /**
     * Get $type
     *
     * @return $type
     **/
    @Schema(description = "")
    public String get$Type() {
        return $type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WorkItemType workItemType = (WorkItemType) o;
        return Objects.equals(this.id, workItemType.id) &&
                Objects.equals(this.name, workItemType.name) &&
                Objects.equals(this.autoAttached, workItemType.autoAttached) &&
                Objects.equals(this.$type, workItemType.$type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, autoAttached, $type);
    }


    @Override
    public String toString() {

        String sb = "class WorkItemType {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    autoAttached: " + toIndentedString(autoAttached) + "\n" +
                "    $type: " + toIndentedString($type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
