services:
  youtrack:
    container_name: youtrack
    image: victoriametrics/vmagent:${YOUTRACK_VERSION}
    volumes:
      - type: volume
        source: ./data
        target: /data


volumes:
  data:
