{
 "title": "SiteSpeed summary metrics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "source ✳️", "query": "prometheus" },
   { "name": "function", "label": "function ❇️", "query": "min, median, p90, max, mean" },
   { "name": "summaryType", "label": "summaryType ✳️", "query": "summary" },
   {
    "name": "browser",
    "label": "browser ✳️",
    "query": {
     "query": "label_values(transferSize_max{summaryType=\"$summaryType\"},browser)"
    }
   },
   {
    "name": "connectivity",
    "label": "connectivity ✳️",
    "query": {
     "query": "label_values(transferSize_max{summaryType=\"$summaryType\", browser=~\"$browser\"},connectivity)"
    }
   },
   {
    "name": "category",
    "label": "category ✴️",
    "query": {
     "query": "label_values(transferSize_max{browser=~\"$browser\", connectivity=~\"$connectivity\", summaryType=\"$summaryType\"},category)"
    }
   },
   {
    "name": "group",
    "label": "group *️⃣",
    "query": {
     "query": "label_values(transferSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\"},group)"
    }
   },
   {
    "name": "testtype",
    "label": "testtype *️⃣",
    "query": {
     "query": "label_values(transferSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\"},testtype)"
    }
   },
   {
    "name": "testName",
    "label": "testName *️⃣",
    "query": {
     "query": "label_values(transferSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testtype=~\"$testtype\"},testName)"
    }
   },
   {
    "name": "contentType",
    "label": "contentType ✳️",
    "query": {
     "query": "label_values(transferSize_max{group=~\"$group\", testtype=~\"$testtype\", testName=~\"$testName\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\"},contentType)"
    }
   },
   {
    "name": "http_code",
    "label": "http_code ✳️",
    "query": {
     "query": "{__name__=~\"^_[0-9]+_max$\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"}"
    }
   },
   {
    "name": "malt_const",
    "query": "APP_ENTRY_CORE_LOADING,\nAPP_ENTRY,\nCORE_DEPENDENCIES_EVAL,\nCORE_INITIALIZATIONS,\nAPP_ACTIVATOR_MODULE,\nAUTHORIZATION_STAGE,\nCORE_INIT,\nFIRST_BYTE,\nCORE_TASK_QUEUE,\nBOARD_MODULE,\nBOARD_TRANSLATOR_SUBSCRIBE,\nBOARD_ROUTE,\nBOARD_CONNECT_REQUEST_STAGE,\nSPACE_CONNECTION_STAGE,\nBOARD_CONNECTION,\nCANVAS_LOADING_STAGE,\nWIDGETS_IDS_RECEIVED,\nWS_WIDGETS_DATA_LOADED,\nPURE_CANVAS_OBJECTS_CREATION,\nALL_WIDGETS_ARE_LOADED,\nCANVAS_DATA,\nFULL_CANVAS_OBJECTS_CREATION,\nBOARD_UI_RENDERED,\nALL_VISUALS_ARE_UPDATED_ONCE,\nALL_RESOURCE_META_INFO_LOADED,\nUI_SYSTEM_INITIALIZED,\nBOARD_UI_MOUNTED,\nBOARD_LOADED_MILESTONE_1,\nALL_RESOURCE_URLS_LOADED,\nBOARD_LOADED_MILESTONE_2,\nINHOUSE_PLUGINS_STARTED,\nBOARD_LOADED_MILESTONE_3"
   },
   {
    "name": "userTimings_measures",
    "label": "userTimings measures ✳️",
    "query": {
     "query": "{__name__=~\"^(.+)_max$\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"}"
    }
   },
   {
    "name": "userTimings_measures_MALT",
    "label": "userTimings_measures_MALT ✳️",
    "query": {
     "query": "{__name__=~\"^(MALT.+)_max$\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"}"
    }
   },
   {
    "name": "userTimings_measures_Other",
    "label": "userTimings_measures_Other ✳️",
    "query": {
     "query": "{__name__=~\"^([^M][^A][^L][^T].+)_max$\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"}"
    }
   },
   {
    "name": "userTimings_marks",
    "label": "userTimings_marks ✳️",
    "query": {
     "query": "{__name__=~\"^(.+)_max$\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"marks\"}"
    }
   },
   {
    "name": "visualMetrics",
    "query": "VisualReadiness, SpeedIndex, FirstVisualChange, VisualComplete85, VisualComplete95, VisualComplete99, LastVisualChange"
   },
   {
    "name": "other_metric_time",
    "query": "firstPaint,\nparseHTML,\nstyleLayout,\npaintCompositeRender,\nscriptParseCompile,\nscriptEvaluation,\ngarbageCollection,\ntotalDuration,\ntotalBlockingTime"
   },
   {
    "name": "other_metric_count",
    "query": "other,\ntasks,\nmaxPotentialFid"
   }
  ]
 },
 "panels": [
  {
   "title": "browsertime (summary): other metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "timings: other metrics",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "{__name__=~\"${other_metric_time:regex}_${function}\", summaryType=\"$summaryType\",   origin=\"browsertime\", timings=\"\"}"
      }
     ]
    },
    {
     "title": "timings: other metrics (count)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"${other_metric_count:regex}_${function}\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"\"}",
       "legendFormat": "{{__name__}} - {{testName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "browsertime (summary): timings: pageTimings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "timings: pageTimings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\".+_${function}\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"pageTimings\"}",
     "legendFormat": "{{__name__}} - {{testName}}"
    }
   ]
  },
  {
   "title": "browsertime (summary): timings: visualMetrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "timings: visualMetrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "{__name__=~\".+_${function:raw}\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"}",
     "legendFormat": "{{__name__}} - {{testName}}"
    }
   ]
  },
  {
   "title": "timings: visualMetrics (${function})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(LastVisualChange_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "LastVisualChange"
    },
    {
     "expr": "avg(VisualComplete99_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "VisualComplete99"
    },
    {
     "expr": "avg(VisualComplete95_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "VisualComplete95"
    },
    {
     "expr": "avg(VisualComplete85_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "VisualComplete85"
    },
    {
     "expr": "avg(FirstVisualChange_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "FirstVisualChange"
    },
    {
     "expr": "avg(SpeedIndex_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "SpeedIndex"
    },
    {
     "expr": "avg(VisualReadiness_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "VisualReadiness"
    }
   ]
  },
  {
   "title": "visualMetrics: $visualMetrics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "repeat": "visualMetrics",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(${visualMetrics:raw}_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg(${visualMetrics:raw}_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "90%"
    },
    {
     "expr": "avg(${visualMetrics:raw}_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "median"
    },
    {
     "expr": "min(${visualMetrics:raw}_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg(${visualMetrics:raw}_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "visualMetrics: $visualMetrics (${function} only)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "repeat": "visualMetrics",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(${visualMetrics:raw}_${function}{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", timings=\"visualMetrics\"})",
     "legendFormat": "${function}"
    }
   ]
  },
  {
   "title": "browsertime (summary): userTimings: measures",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "userTimings / measures: MALT",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"MALT__.+_mean\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"}",
       "legendFormat": "{{__name__}} - {{testName}}"
      }
     ]
    },
    {
     "title": "userTimings / measures: non MALT",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"^([^M][^A][^L][^T]).+_mean\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"}",
       "legendFormat": "{{__name__}} - {{testName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "browsertime (summary): userTimings: measures: MALT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "measures: $userTimings_measures_MALT",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
     "repeat": "userTimings_measures_MALT",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(${userTimings_measures_MALT:raw}_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(${userTimings_measures_MALT:raw}_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(${userTimings_measures_MALT:raw}_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(${userTimings_measures_MALT:raw}_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(${userTimings_measures_MALT:raw}_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "browsertime (summary): userTimings: measures: Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "title": "measures: $userTimings_measures_Other",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 71 },
     "repeat": "userTimings_measures_Other",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max({__name__=\"${userTimings_measures_Other:raw}_max\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg({__name__=\"${userTimings_measures_Other:raw}_p90\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg({__name__=\"${userTimings_measures_Other:raw}_median\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min({__name__=\"${userTimings_measures_Other:raw}_min\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg({__name__=\"${userTimings_measures_Other:raw}_mean\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"measures\"})",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "browsertime (summary): userTimings: marks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "userTimings / marks",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"${userTimings_marks:regex}_mean\", summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"browsertime\", userTimings=\"marks\"}",
       "legendFormat": "{{__name__}} - {{testName}}"
      }
     ]
    }
   ]
  },
  {
   "title": "pagexray (summary) requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(requests_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(requests_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(requests_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(requests_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(requests_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "requests: firstParty",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(requests_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(requests_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(requests_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(requests_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(requests_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "requests: thirdParty",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(requests_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(requests_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(requests_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(requests_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(requests_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "contentSize",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(contentSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(contentSize_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(contentSize_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(contentSize_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(contentSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "contentSize: firstParty",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(contentSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(contentSize_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(contentSize_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(contentSize_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(contentSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "contentSize: thirdParty",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(contentSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(contentSize_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(contentSize_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(contentSize_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(contentSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "transferSize",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(transferSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(transferSize_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(transferSize_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(transferSize_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(transferSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", party=\"\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "transferSize: firstParty",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(transferSize_max{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(transferSize_p90{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(transferSize_median{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(transferSize_min{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(transferSize_mean{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"firstParty\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "transferSize: thirdParty",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(transferSize_max{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(transferSize_p90{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(transferSize_median{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(transferSize_min{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(transferSize_mean{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\", party=\"thirdParty\", contentType=\"\"})",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "pagexray (summary) responses: HTTP Codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "${http_code}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "{__name__=~\"_[0-9]+_mean\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "${http_code}",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
     "repeat": "http_code",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(_${http_code:raw}_max{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(_${http_code:raw}_p90{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(_${http_code:raw}_median{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(_${http_code:raw}_min{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(_${http_code:raw}_mean{group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", summaryType=\"summary\"})",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "pagexray (summary) responses by contentType: transferSize, contentSize, requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "requests (mean): ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(contentType) (requests_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\",  contentType=~\"$contentType\"})",
       "legendFormat": "{{contentType}}"
      }
     ]
    },
    {
     "title": "contentSize (mean): ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(contentType) (contentSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "{{contentType}}"
      }
     ]
    },
    {
     "title": "transferSize (mean): ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(contentType) (transferSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\",  contentType=~\"$contentType\"})",
       "legendFormat": "{{contentType}}"
      }
     ]
    },
    {
     "title": "requests (mean) stack: ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(contentType) (requests_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\",contentType=~\"$contentType\"})",
       "legendFormat": "{{contentType}}"
      }
     ]
    },
    {
     "title": "contentSize (mean) stack: ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(contentType) (contentSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "{{contentType}}"
      }
     ]
    },
    {
     "title": "transferSize (mean) stack: ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg by(contentType) (transferSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\",contentType=~\"$contentType\"})",
       "legendFormat": "{{contentType}}"
      }
     ]
    },
    {
     "title": "requests: ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 93 },
     "repeat": "contentType",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max (requests_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg (requests_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(requests_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(requests_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(requests_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "contentSize: ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 93 },
     "repeat": "contentType",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max  (contentSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(contentSize_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(contentSize_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(contentSize_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(contentSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "transferSize: ${contentType}",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 93 },
     "repeat": "contentType",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max (transferSize_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(transferSize_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(transferSize_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(transferSize_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(transferSize_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\", contentType=~\"$contentType\"})",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  },
  {
   "title": "pagexray (summary) cookies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 },
   "collapsed": true,
   "panels": [
    {
     "title": "domains",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(domains_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(domains_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(domains_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(domains_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(domains_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "cookies",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(cookies_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(cookies_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(cookies_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(cookies_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(cookies_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "lastModifiedStats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(lastModifiedStats_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(lastModifiedStats_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(lastModifiedStats_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(lastModifiedStats_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(lastModifiedStats_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "mean"
      }
     ]
    },
    {
     "title": "expireStats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(expireStats_max{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg(expireStats_p90{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "90%"
      },
      {
       "expr": "avg(expireStats_median{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "median"
      },
      {
       "expr": "min(expireStats_min{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg(expireStats_mean{summaryType=\"$summaryType\", browser=~\"$browser\", connectivity=~\"$connectivity\", category=~\"$category\", group=~\"$group\", testName=~\"$testName\", testtype=~\"$testtype\", origin=\"pagexray\"})",
       "legendFormat": "mean"
      }
     ]
    }
   ]
  }
 ]
}