{
 "title": "Sitespeed Summary",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "influxdb" },
   {
    "name": "function",
    "query": "min, mean, median, p90, max, stddev"
   },
   { "name": "category", "query": "default" },
   { "name": "project", "query": "site, camp, enterprise" },
   {
    "name": "testName",
    "query": "SHOW TAG VALUES WITH KEY=\"testName\" WHERE summaryType='pageSummary'  and category =~ /^${category:regex}$/  and project =~ /^${project:regex}$/"
   },
   {
    "name": "group",
    "query": "SHOW TAG VALUES WITH KEY=\"group\" WHERE summaryType='pageSummary' and testName =~ /^${testName:regex}$/\n and category =~ /^${category:regex}$/  and project =~ /^${project:regex}$/"
   },
   {
    "name": "page",
    "query": "SHOW TAG VALUES WITH KEY=\"page\" WHERE summaryType='pageSummary' and testName =~ /^${testName:regex}$/ and \"group\" =~ /^${group}$/\n and category =~ /^${category:regex}$/  and project =~ /^${project:regex}$/"
   },
   { "name": "browser", "query": "chrome" },
   {
    "name": "contentType",
    "query": "image,\nhtml,\njson,\njavascript,\nsvg,\ncss,\nfont"
   }
  ]
 },
 "panels": [
  {
   "title": "[Range] Largest Contentful Paint (LCP)",
   "type": "table",
   "description": "The Largest Contentful Paint (LCP) metric reports the render time of the largest content element visible in the viewport.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "largestContentfulPaint",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] Speed Index",
   "type": "table",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] CLS",
   "type": "table",
   "description": "Cumulative Layout Shift (CLS) measures the sum total of individual layout shift scores for the unexpected layout shift that occurs during maximum session window with 1 second gap, capped at 5 seconds. This is a Chrome only metric.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "cumulativeLayoutShift",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] Largest Contentful Paint (LCP)",
   "type": "table",
   "description": "The Largest Contentful Paint (LCP) metric reports the render time of the largest content element visible in the viewport.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "largestContentfulPaint",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] Speed Index",
   "type": "table",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] CLS",
   "type": "table",
   "description": "Cumulative Layout Shift (CLS) measures the sum total of individual layout shift scores for the unexpected layout shift that occurs during maximum session window with 1 second gap, capped at 5 seconds. This is a Chrome only metric.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "cumulativeLayoutShift",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] Largest Contentful Paint (LCP)",
   "type": "table",
   "description": "The Largest Contentful Paint (LCP) metric reports the render time of the largest content element visible in the viewport.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "largestContentfulPaint",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] Speed Index",
   "type": "table",
   "description": "The Speed Index is the average time at which visible parts of the page are displayed. It is expressed in milliseconds and dependent on size of the view port. It was created by Pat Meenan",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "[Range] CLS",
   "type": "table",
   "description": "Cumulative Layout Shift (CLS) measures the sum total of individual layout shift scores for the unexpected layout shift that occurs during maximum session window with 1 second gap, capped at 5 seconds. This is a Chrome only metric.",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_page",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "page" ], "type": "tag" }
     ],
     "measurement": "cumulativeLayoutShift",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  { "title": "Page metrics: ${page}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "page" },
  {
   "title": "Visual Metrics [$function]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Fully Loaded",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fullyLoaded",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "LastVisualChange",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LastVisualChange",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "Last CPU long task",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "lastLongTask",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "LargestContentfulPaint",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LargestContentfulPaint",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "ContenfulSpeedIndex",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ContentfulSpeedIndex",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "LargestImage",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LargestImage",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "SpeedIndex",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SpeedIndex",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "FirstVisualChange",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FirstVisualChange",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "TTFB",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ttfb",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    },
    {
     "alias": "largestContentfulPaint",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "testName" ], "type": "tag" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "page" ], "type": "tag" },
      { "params": [ "browser" ], "type": "tag" },
      { "params": [ "connectivity" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "largestContentfulPaint",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  { "title": "Page Vitals", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 16 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Transfer Size",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "transferSize",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "contentType", "operator": "!~", "value": "/^.+$/" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Requests",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "DOM Elements",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "domElements",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  { "title": "Google Web Vitals", "type": "text", "gridPos": { "h": 1, "w": 6, "x": 18, "y": 23 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FCP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "first-contentful-paint",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "LCP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "largestContentfulPaint",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CLS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "cumulativeLayoutShift",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TBT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "totalBlockingTime",
     "select": [
      [
       { "params": [ "${function}" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
      { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
      { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
      { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
      { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
      { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Link",
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 28 },
   "options": {
    "content": "<h1>\n🔗 <a target=\"blank ${page}\" href=\"/d/sitespeed?${__all_variables}&${__url_time_range}\">\nLink to Details\n</a>\n</h1>"
   }
  },
  {
   "title": "Google Web Vitals trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Contentful Paint",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "measurement": "first-contentful-paint",
       "query": "from(bucket: \"sitespeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firstContentfulPaint\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])\n  |> yield(name: \"max\")",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "paintTiming", "operator": "=", "value": "first-contentful-paint" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "timings" }
       ]
      },
      {
       "query": "import \"regexp\"\nimport \"experimental\"\n\nnormalizeTime = (t) => {\n  normalized =\n    if regexp.matchRegexpString(r: /[n|u|s|m|h|d|w|o|y]/, v: t) then experimental.addDuration(d: duration(v: t), to: now())\n    else time(v: t)\n  return normalized\n}\n\nhistoricalPeriod = -7d\nhistoricalStart = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStart)))\nhistoricalStop = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStop)))\n\n\n\nfrom(bucket: \"sitespeed\")\n  |> range(start: historicalStart, stop: historicalStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"firstContentfulPaint\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> timeShift(duration: - historicalPeriod, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Largest Contentful Paint",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "measurement": "first-contentful-paint",
       "query": "from(bucket: \"sitespeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"largestContentfulPaint\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])\n  |> yield(name: \"max\")",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "paintTiming", "operator": "=", "value": "first-contentful-paint" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "timings" }
       ]
      },
      {
       "query": "import \"regexp\"\nimport \"experimental\"\n\nnormalizeTime = (t) => {\n  normalized =\n    if regexp.matchRegexpString(r: /[n|u|s|m|h|d|w|o|y]/, v: t) then experimental.addDuration(d: duration(v: t), to: now())\n    else time(v: t)\n  return normalized\n}\n\nhistoricalPeriod = -7d\nhistoricalStart = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStart)))\nhistoricalStop = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStop)))\n\n\n\nfrom(bucket: \"sitespeed\")\n  |> range(start: historicalStart, stop: historicalStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"largestContentfulPaint\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> timeShift(duration: - historicalPeriod, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Total Blocking Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "measurement": "first-contentful-paint",
       "query": "from(bucket: \"sitespeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])\n  |> yield(name: \"max\")",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "paintTiming", "operator": "=", "value": "first-contentful-paint" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "timings" }
       ]
      },
      {
       "query": "import \"regexp\"\nimport \"experimental\"\n\nnormalizeTime = (t) => {\n  normalized =\n    if regexp.matchRegexpString(r: /[n|u|s|m|h|d|w|o|y]/, v: t) then experimental.addDuration(d: duration(v: t), to: now())\n    else time(v: t)\n  return normalized\n}\n\nhistoricalPeriod = -7d\nhistoricalStart = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStart)))\nhistoricalStop = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStop)))\n\n\n\nfrom(bucket: \"sitespeed\")\n  |> range(start: historicalStart, stop: historicalStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"totalBlockingTime\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> timeShift(duration: - historicalPeriod, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "Cumulative Layout Shift",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "measurement": "first-contentful-paint",
       "query": "from(bucket: \"sitespeed\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulativeLayoutShift\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> drop(columns: [\"_field\"])\n  |> yield(name: \"max\")",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "paintTiming", "operator": "=", "value": "first-contentful-paint" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "timings" }
       ]
      },
      {
       "query": "import \"regexp\"\nimport \"experimental\"\n\nnormalizeTime = (t) => {\n  normalized =\n    if regexp.matchRegexpString(r: /[n|u|s|m|h|d|w|o|y]/, v: t) then experimental.addDuration(d: duration(v: t), to: now())\n    else time(v: t)\n  return normalized\n}\n\nhistoricalPeriod = -7d\nhistoricalStart = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStart)))\nhistoricalStop = experimental.addDuration(d: historicalPeriod, to: normalizeTime(t: string(v: v.timeRangeStop)))\n\n\n\nfrom(bucket: \"sitespeed\")\n  |> range(start: historicalStart, stop: historicalStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"cumulativeLayoutShift\")\n  |> filter(fn: (r) => r[\"_field\"] == \"max\")\n  |> filter(fn: (r) => r[\"browser\"] =~ /^${browser:regex}$/)\n  |> filter(fn: (r) => r[\"connectivity\"] == \"native\")\n  |> filter(fn: (r) => r[\"group\"] =~ /^${group:regex}$/)\n  |> filter(fn: (r) => r[\"origin\"] == \"browsertime\")\n  |> filter(fn: (r) => r[\"page\"] =~ /^${page:regex}$/)\n  |> filter(fn: (r) => r[\"statistics\"] == \"googleWebVitals\")\n  |> filter(fn: (r) => r[\"summaryType\"] == \"pageSummary\")\n  |> filter(fn: (r) => r[\"testName\"] =~ /^${testName:regex}$/)\n  |> filter(fn: (r) => r[\"category\"] =~ /^${category:regex}$/)\n  |> filter(fn: (r) => r[\"project\"] =~  /^${project:regex}$/)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> timeShift(duration: - historicalPeriod, columns: [\"_start\", \"_stop\", \"_time\"])\n  |> yield(name: \"max\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Google Web Vitals history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Contentful Paint (FCP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "FCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "first-contentful-paint",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "paintTiming", "operator": "=", "value": "first-contentful-paint" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "timings" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Cumulative Layout Shift (CLS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "CLS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "cumulativeLayoutShift",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "pageinfo" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Largest Contentful Paint (LCP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "LCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "largestContentfulPaint",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Blocking Time (TBT)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "TBT",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "totalBlockingTime",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "cpu", "operator": "=", "value": "longTask" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request count",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_page",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "page" ], "type": "tag" },
        { "params": [ "group" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "requests",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Main document timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Main document timings",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_mainDocumentTimings",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "mainDocumentTimings" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/^.+$/",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "mainDocumentTimings", "operator": "=~", "value": "/^.+$/" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "timings" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Size history (first party: ${group})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "contentSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "contentSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "!~", "value": "/^.+$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "transferSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "transferSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "!~", "value": "/^.+$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "${contentType} size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 4.8, "x": 0, "y": 31 },
     "repeat": "contentType",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "contentSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "contentSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^$contentType$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "transferSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "transferSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^$contentType$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Content size per type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_contentType",
       "groupBy": [
        { "params": [ "contentType" ], "type": "tag" }
       ],
       "measurement": "contentSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^.+$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "title": "Transfer size per type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_contentType",
       "groupBy": [
        { "params": [ "contentType" ], "type": "tag" }
       ],
       "measurement": "transferSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^.+$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "firstParty" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Coach history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Coach Score",
     "type": "timeseries",
     "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Best practice",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "score",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "advice", "operator": "=", "value": "bestpractice" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "Privacy",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "score",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "advice", "operator": "=", "value": "privacy" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "Performance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "score",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "advice", "operator": "=", "value": "performance" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "score",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "coach" },
        { "condition": "AND", "key": "advice", "operator": "!~", "value": "/^.+$/" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Axe history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Critical",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "critical",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Serious",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "serious",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Minor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "minor",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Moderate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "moderate",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Critical",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "critical",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "Serious",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "serious",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "Moderate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "moderate",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      },
      {
       "alias": "Minor",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "minor",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "axe" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Navigation Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Navigation timing [${function}]",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_navigationTiming",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "navigationTiming" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "/^.+$/",
       "select": [
        [
         { "params": [ "${function}" ], "type": "field" },
         {
          "params": [],
          "type": "first"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "browser", "operator": "=~", "value": "/^$browser$/" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "browsertime" },
        { "condition": "AND", "key": "statistics", "operator": "=", "value": "timings" },
        { "condition": "AND", "key": "navigationTiming", "operator": "=~", "value": "/^.+$/" },
        { "condition": "AND", "key": "category", "operator": "=~", "value": "/^$category$/" },
        { "condition": "AND", "key": "project", "operator": "=~", "value": "/^$project$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Size history (third party: non ${group})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "contentSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "contentSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "!~", "value": "/^.+$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
       ]
      },
      {
       "alias": "transferSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "transferSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "!~", "value": "/^.+$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
       ]
      }
     ]
    },
    {
     "title": "${contentType} size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
     "repeat": "contentType",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "contentSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "contentSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^$contentType$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
       ]
      },
      {
       "alias": "transferSize",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "transferSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^$contentType$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
       ]
      }
     ]
    },
    {
     "title": "Content size per type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_contentType",
       "groupBy": [
        { "params": [ "contentType" ], "type": "tag" }
       ],
       "measurement": "contentSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^.+$/" }
       ]
      }
     ]
    },
    {
     "title": "Transfer size per type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_contentType",
       "groupBy": [
        { "params": [ "contentType" ], "type": "tag" }
       ],
       "measurement": "transferSize",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "testName", "operator": "=~", "value": "/^$testName$/" },
        { "condition": "AND", "key": "group", "operator": "=~", "value": "/^$group$/" },
        { "condition": "AND", "key": "page", "operator": "=~", "value": "/^$page$/" },
        { "condition": "AND", "key": "summaryType", "operator": "=", "value": "pageSummary" },
        { "condition": "AND", "key": "origin", "operator": "=", "value": "pagexray" },
        { "condition": "AND", "key": "contentType", "operator": "=~", "value": "/^.+$/" },
        { "condition": "AND", "key": "party", "operator": "=", "value": "thirdParty" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "200",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "200",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "*" ], "type": "tag" }
       ],
       "measurement": "200",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "200",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "*" ], "type": "tag" }
       ],
       "measurement": "200",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}