# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
# list of datasources that should be deleted from the database
deleteDatasources:
  - name: influxdb-grafana
    orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: influxdb-grafana
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: influxdb-grafana
    # <string, required> datasource type. Required
    type: influxdb
    # <string, required> access mode. direct or proxy. Required
    access: proxy
    # <int> org id. will default to orgId 1 if not specified
    orgId: 1
    # <string> url
    url: http://influxdb_v2:8086
    # <bool> allow users to edit datasources from the UI.
    editable: false
    # <bool> enable/disable basic auth
    basicAuth: false
    # <string> auth username
    user: grafana
    jsonData:
      httpMode: POST
      dbName: grafana
    # <string> json object of data that will be encrypted.
    secureJsonData:
      # <string> auth password
      password: password