# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
# list of datasources that should be deleted from the database
deleteDatasources:
  - name: prometheus
    orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  - name: prometheus
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true