/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * AccessGrantOptionList
 */


public class AccessGrantOptionList {
    @SerializedName("hasAlready")
    private Boolean hasAlready = null;

    @SerializedName("options")
    private List<AccessGrantOption> options = null;

    public AccessGrantOptionList hasAlready(Boolean hasAlready) {
        this.hasAlready = hasAlready;
        return this;
    }

    /**
     * Get hasAlready
     *
     * @return hasAlready
     **/
    @Schema(description = "")
    public Boolean isHasAlready() {
        return hasAlready;
    }

    public void setHasAlready(Boolean hasAlready) {
        this.hasAlready = hasAlready;
    }

    public AccessGrantOptionList options(List<AccessGrantOption> options) {
        this.options = options;
        return this;
    }

    public AccessGrantOptionList addOptionsItem(AccessGrantOption optionsItem) {
        if (this.options == null) {
            this.options = new ArrayList<AccessGrantOption>();
        }
        this.options.add(optionsItem);
        return this;
    }

    /**
     * Get options
     *
     * @return options
     **/
    @Schema(description = "")
    public List<AccessGrantOption> getOptions() {
        return options;
    }

    public void setOptions(List<AccessGrantOption> options) {
        this.options = options;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AccessGrantOptionList accessGrantOptionList = (AccessGrantOptionList) o;
        return Objects.equals(this.hasAlready, accessGrantOptionList.hasAlready) &&
                Objects.equals(this.options, accessGrantOptionList.options);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hasAlready, options);
    }


    @Override
    public String toString() {

        String sb = "class AccessGrantOptionList {\n" +
                "    hasAlready: " + toIndentedString(hasAlready) + "\n" +
                "    options: " + toIndentedString(options) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
