/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ApplicationPasswordsPage
 */


public class ApplicationPasswordsPage extends BasePage {
    @SerializedName("applicationPasswords")
    private List<ApplicationPassword> applicationPasswords = null;

    public ApplicationPasswordsPage applicationPasswords(List<ApplicationPassword> applicationPasswords) {
        this.applicationPasswords = applicationPasswords;
        return this;
    }

    public ApplicationPasswordsPage addApplicationPasswordsItem(ApplicationPassword applicationPasswordsItem) {
        if (this.applicationPasswords == null) {
            this.applicationPasswords = new ArrayList<ApplicationPassword>();
        }
        this.applicationPasswords.add(applicationPasswordsItem);
        return this;
    }

    /**
     * Get applicationPasswords
     *
     * @return applicationPasswords
     **/
    @Schema(description = "")
    public List<ApplicationPassword> getApplicationPasswords() {
        return applicationPasswords;
    }

    public void setApplicationPasswords(List<ApplicationPassword> applicationPasswords) {
        this.applicationPasswords = applicationPasswords;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApplicationPasswordsPage applicationPasswordsPage = (ApplicationPasswordsPage) o;
        return Objects.equals(this.applicationPasswords, applicationPasswordsPage.applicationPasswords) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(applicationPasswords, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class ApplicationPasswordsPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    applicationPasswords: " + toIndentedString(applicationPasswords) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
