/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ApprovedScope
 */


public class ApprovedScope {
    @SerializedName("id")
    private String id = null;

    @SerializedName("client")
    private Service client = null;

    @SerializedName("scope")
    private List<Service> scope = null;

    @SerializedName("user")
    private User user = null;

    @SerializedName("expiresOn")
    private Long expiresOn = null;

    public ApprovedScope id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ApprovedScope client(Service client) {
        this.client = client;
        return this;
    }

    /**
     * Get client
     *
     * @return client
     **/
    @Schema(description = "")
    public Service getClient() {
        return client;
    }

    public void setClient(Service client) {
        this.client = client;
    }

    public ApprovedScope scope(List<Service> scope) {
        this.scope = scope;
        return this;
    }

    public ApprovedScope addScopeItem(Service scopeItem) {
        if (this.scope == null) {
            this.scope = new ArrayList<Service>();
        }
        this.scope.add(scopeItem);
        return this;
    }

    /**
     * Get scope
     *
     * @return scope
     **/
    @Schema(description = "")
    public List<Service> getScope() {
        return scope;
    }

    public void setScope(List<Service> scope) {
        this.scope = scope;
    }

    public ApprovedScope user(User user) {
        this.user = user;
        return this;
    }

    /**
     * Get user
     *
     * @return user
     **/
    @Schema(description = "")
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public ApprovedScope expiresOn(Long expiresOn) {
        this.expiresOn = expiresOn;
        return this;
    }

    /**
     * Get expiresOn
     *
     * @return expiresOn
     **/
    @Schema(description = "")
    public Long getExpiresOn() {
        return expiresOn;
    }

    public void setExpiresOn(Long expiresOn) {
        this.expiresOn = expiresOn;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApprovedScope approvedScope = (ApprovedScope) o;
        return Objects.equals(this.id, approvedScope.id) &&
                Objects.equals(this.client, approvedScope.client) &&
                Objects.equals(this.scope, approvedScope.scope) &&
                Objects.equals(this.user, approvedScope.user) &&
                Objects.equals(this.expiresOn, approvedScope.expiresOn);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, client, scope, user, expiresOn);
    }


    @Override
    public String toString() {

        String sb = "class ApprovedScope {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    client: " + toIndentedString(client) + "\n" +
                "    scope: " + toIndentedString(scope) + "\n" +
                "    user: " + toIndentedString(user) + "\n" +
                "    expiresOn: " + toIndentedString(expiresOn) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
