/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ApprovedscopesPage
 */


public class ApprovedscopesPage extends BasePage {
    @SerializedName("approvedscopes")
    private List<ApprovedScope> approvedscopes = null;

    public ApprovedscopesPage approvedscopes(List<ApprovedScope> approvedscopes) {
        this.approvedscopes = approvedscopes;
        return this;
    }

    public ApprovedscopesPage addApprovedscopesItem(ApprovedScope approvedscopesItem) {
        if (this.approvedscopes == null) {
            this.approvedscopes = new ArrayList<ApprovedScope>();
        }
        this.approvedscopes.add(approvedscopesItem);
        return this;
    }

    /**
     * Get approvedscopes
     *
     * @return approvedscopes
     **/
    @Schema(description = "")
    public List<ApprovedScope> getApprovedscopes() {
        return approvedscopes;
    }

    public void setApprovedscopes(List<ApprovedScope> approvedscopes) {
        this.approvedscopes = approvedscopes;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApprovedscopesPage approvedscopesPage = (ApprovedscopesPage) o;
        return Objects.equals(this.approvedscopes, approvedscopesPage.approvedscopes) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(approvedscopes, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class ApprovedscopesPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    approvedscopes: " + toIndentedString(approvedscopes) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
