/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * AuthRequest
 */


public class AuthRequest {
    @SerializedName("userId")
    private String userId = null;

    @SerializedName("credentials")
    private Credentials credentials = null;

    public AuthRequest userId(String userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Get userId
     *
     * @return userId
     **/
    @Schema(description = "")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public AuthRequest credentials(Credentials credentials) {
        this.credentials = credentials;
        return this;
    }

    /**
     * Get credentials
     *
     * @return credentials
     **/
    @Schema(description = "")
    public Credentials getCredentials() {
        return credentials;
    }

    public void setCredentials(Credentials credentials) {
        this.credentials = credentials;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AuthRequest authRequest = (AuthRequest) o;
        return Objects.equals(this.userId, authRequest.userId) &&
                Objects.equals(this.credentials, authRequest.credentials);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userId, credentials);
    }


    @Override
    public String toString() {

        String sb = "class AuthRequest {\n" +
                "    userId: " + toIndentedString(userId) + "\n" +
                "    credentials: " + toIndentedString(credentials) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
