/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * BackupStatus
 */


public class BackupStatus {
    @SerializedName("inProgress")
    private Boolean inProgress = null;

    @SerializedName("savedData")
    private List<BackupData> savedData = null;

    public BackupStatus inProgress(Boolean inProgress) {
        this.inProgress = inProgress;
        return this;
    }

    /**
     * Get inProgress
     *
     * @return inProgress
     **/
    @Schema(description = "")
    public Boolean isInProgress() {
        return inProgress;
    }

    public void setInProgress(Boolean inProgress) {
        this.inProgress = inProgress;
    }

    public BackupStatus savedData(List<BackupData> savedData) {
        this.savedData = savedData;
        return this;
    }

    public BackupStatus addSavedDataItem(BackupData savedDataItem) {
        if (this.savedData == null) {
            this.savedData = new ArrayList<BackupData>();
        }
        this.savedData.add(savedDataItem);
        return this;
    }

    /**
     * Get savedData
     *
     * @return savedData
     **/
    @Schema(description = "")
    public List<BackupData> getSavedData() {
        return savedData;
    }

    public void setSavedData(List<BackupData> savedData) {
        this.savedData = savedData;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BackupStatus backupStatus = (BackupStatus) o;
        return Objects.equals(this.inProgress, backupStatus.inProgress) &&
                Objects.equals(this.savedData, backupStatus.savedData);
    }

    @Override
    public int hashCode() {
        return Objects.hash(inProgress, savedData);
    }


    @Override
    public String toString() {

        String sb = "class BackupStatus {\n" +
                "    inProgress: " + toIndentedString(inProgress) + "\n" +
                "    savedData: " + toIndentedString(savedData) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
