/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CertificatesPage
 */


public class CertificatesPage extends BasePage {
    @SerializedName("certificates")
    private List<Certificate> certificates = null;

    public CertificatesPage certificates(List<Certificate> certificates) {
        this.certificates = certificates;
        return this;
    }

    public CertificatesPage addCertificatesItem(Certificate certificatesItem) {
        if (this.certificates == null) {
            this.certificates = new ArrayList<Certificate>();
        }
        this.certificates.add(certificatesItem);
        return this;
    }

    /**
     * Get certificates
     *
     * @return certificates
     **/
    @Schema(description = "")
    public List<Certificate> getCertificates() {
        return certificates;
    }

    public void setCertificates(List<Certificate> certificates) {
        this.certificates = certificates;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CertificatesPage certificatesPage = (CertificatesPage) o;
        return Objects.equals(this.certificates, certificatesPage.certificates) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(certificates, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class CertificatesPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    certificates: " + toIndentedString(certificates) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
