/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DuplicateUserMergeRequest
 */


public class DuplicateUserMergeRequest {
    @SerializedName("all")
    private Boolean all = null;

    @SerializedName("clusters")
    private List<DuplicateUserCluster> clusters = null;

    public DuplicateUserMergeRequest all(Boolean all) {
        this.all = all;
        return this;
    }

    /**
     * Get all
     *
     * @return all
     **/
    @Schema(description = "")
    public Boolean isAll() {
        return all;
    }

    public void setAll(Boolean all) {
        this.all = all;
    }

    public DuplicateUserMergeRequest clusters(List<DuplicateUserCluster> clusters) {
        this.clusters = clusters;
        return this;
    }

    public DuplicateUserMergeRequest addClustersItem(DuplicateUserCluster clustersItem) {
        if (this.clusters == null) {
            this.clusters = new ArrayList<DuplicateUserCluster>();
        }
        this.clusters.add(clustersItem);
        return this;
    }

    /**
     * Get clusters
     *
     * @return clusters
     **/
    @Schema(description = "")
    public List<DuplicateUserCluster> getClusters() {
        return clusters;
    }

    public void setClusters(List<DuplicateUserCluster> clusters) {
        this.clusters = clusters;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DuplicateUserMergeRequest duplicateUserMergeRequest = (DuplicateUserMergeRequest) o;
        return Objects.equals(this.all, duplicateUserMergeRequest.all) &&
                Objects.equals(this.clusters, duplicateUserMergeRequest.clusters);
    }

    @Override
    public int hashCode() {
        return Objects.hash(all, clusters);
    }


    @Override
    public String toString() {

        String sb = "class DuplicateUserMergeRequest {\n" +
                "    all: " + toIndentedString(all) + "\n" +
                "    clusters: " + toIndentedString(clusters) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
