/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DuplicateUserSearchResult
 */


public class DuplicateUserSearchResult {
    @SerializedName("id")
    private String id = null;

    @SerializedName("progress")
    private DuplicateSearchProgress progress = null;

    @SerializedName("clusterCount")
    private Integer clusterCount = null;

    @SerializedName("clusters")
    private List<DuplicateUserCluster> clusters = null;

    public DuplicateUserSearchResult id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public DuplicateUserSearchResult progress(DuplicateSearchProgress progress) {
        this.progress = progress;
        return this;
    }

    /**
     * Get progress
     *
     * @return progress
     **/
    @Schema(description = "")
    public DuplicateSearchProgress getProgress() {
        return progress;
    }

    public void setProgress(DuplicateSearchProgress progress) {
        this.progress = progress;
    }

    public DuplicateUserSearchResult clusterCount(Integer clusterCount) {
        this.clusterCount = clusterCount;
        return this;
    }

    /**
     * Get clusterCount
     *
     * @return clusterCount
     **/
    @Schema(description = "")
    public Integer getClusterCount() {
        return clusterCount;
    }

    public void setClusterCount(Integer clusterCount) {
        this.clusterCount = clusterCount;
    }

    public DuplicateUserSearchResult clusters(List<DuplicateUserCluster> clusters) {
        this.clusters = clusters;
        return this;
    }

    public DuplicateUserSearchResult addClustersItem(DuplicateUserCluster clustersItem) {
        if (this.clusters == null) {
            this.clusters = new ArrayList<DuplicateUserCluster>();
        }
        this.clusters.add(clustersItem);
        return this;
    }

    /**
     * Get clusters
     *
     * @return clusters
     **/
    @Schema(description = "")
    public List<DuplicateUserCluster> getClusters() {
        return clusters;
    }

    public void setClusters(List<DuplicateUserCluster> clusters) {
        this.clusters = clusters;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DuplicateUserSearchResult duplicateUserSearchResult = (DuplicateUserSearchResult) o;
        return Objects.equals(this.id, duplicateUserSearchResult.id) &&
                Objects.equals(this.progress, duplicateUserSearchResult.progress) &&
                Objects.equals(this.clusterCount, duplicateUserSearchResult.clusterCount) &&
                Objects.equals(this.clusters, duplicateUserSearchResult.clusters);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, progress, clusterCount, clusters);
    }


    @Override
    public String toString() {

        String sb = "class DuplicateUserSearchResult {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    progress: " + toIndentedString(progress) + "\n" +
                "    clusterCount: " + toIndentedString(clusterCount) + "\n" +
                "    clusters: " + toIndentedString(clusters) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
