/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * DuplicateUser
 */


public class DuplicateUser {
    @SerializedName("user")
    private User user = null;

    @SerializedName("reasonFields")
    private List<String> reasonFields = null;

    public DuplicateUser user(User user) {
        this.user = user;
        return this;
    }

    /**
     * Get user
     *
     * @return user
     **/
    @Schema(description = "")
    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public DuplicateUser reasonFields(List<String> reasonFields) {
        this.reasonFields = reasonFields;
        return this;
    }

    public DuplicateUser addReasonFieldsItem(String reasonFieldsItem) {
        if (this.reasonFields == null) {
            this.reasonFields = new ArrayList<String>();
        }
        this.reasonFields.add(reasonFieldsItem);
        return this;
    }

    /**
     * Get reasonFields
     *
     * @return reasonFields
     **/
    @Schema(description = "")
    public List<String> getReasonFields() {
        return reasonFields;
    }

    public void setReasonFields(List<String> reasonFields) {
        this.reasonFields = reasonFields;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DuplicateUser duplicateUser = (DuplicateUser) o;
        return Objects.equals(this.user, duplicateUser.user) &&
                Objects.equals(this.reasonFields, duplicateUser.reasonFields);
    }

    @Override
    public int hashCode() {
        return Objects.hash(user, reasonFields);
    }


    @Override
    public String toString() {

        String sb = "class DuplicateUser {\n" +
                "    user: " + toIndentedString(user) + "\n" +
                "    reasonFields: " + toIndentedString(reasonFields) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
