/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Error
 */


public class Error {
    @SerializedName("error")
    private String error = null;

    @SerializedName("error_code")
    private Integer errorCode = null;

    @SerializedName("error_description")
    private String errorDescription = null;

    @SerializedName("error_developer_message")
    private String errorDeveloperMessage = null;

    @SerializedName("error_uri")
    private String errorUri = null;

    @SerializedName("error_field")
    private String errorField = null;

    @SerializedName("error_params")
    private List<NameValue> errorParams = null;

    public Error error(String error) {
        this.error = error;
        return this;
    }

    /**
     * Get error
     *
     * @return error
     **/
    @Schema(description = "")
    public String getError() {
        return error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public Error errorCode(Integer errorCode) {
        this.errorCode = errorCode;
        return this;
    }

    /**
     * Get errorCode
     *
     * @return errorCode
     **/
    @Schema(description = "")
    public Integer getErrorCode() {
        return errorCode;
    }

    public void setErrorCode(Integer errorCode) {
        this.errorCode = errorCode;
    }

    public Error errorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
        return this;
    }

    /**
     * Get errorDescription
     *
     * @return errorDescription
     **/
    @Schema(description = "")
    public String getErrorDescription() {
        return errorDescription;
    }

    public void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }

    public Error errorDeveloperMessage(String errorDeveloperMessage) {
        this.errorDeveloperMessage = errorDeveloperMessage;
        return this;
    }

    /**
     * Get errorDeveloperMessage
     *
     * @return errorDeveloperMessage
     **/
    @Schema(description = "")
    public String getErrorDeveloperMessage() {
        return errorDeveloperMessage;
    }

    public void setErrorDeveloperMessage(String errorDeveloperMessage) {
        this.errorDeveloperMessage = errorDeveloperMessage;
    }

    public Error errorUri(String errorUri) {
        this.errorUri = errorUri;
        return this;
    }

    /**
     * Get errorUri
     *
     * @return errorUri
     **/
    @Schema(description = "")
    public String getErrorUri() {
        return errorUri;
    }

    public void setErrorUri(String errorUri) {
        this.errorUri = errorUri;
    }

    public Error errorField(String errorField) {
        this.errorField = errorField;
        return this;
    }

    /**
     * Get errorField
     *
     * @return errorField
     **/
    @Schema(description = "")
    public String getErrorField() {
        return errorField;
    }

    public void setErrorField(String errorField) {
        this.errorField = errorField;
    }

    public Error errorParams(List<NameValue> errorParams) {
        this.errorParams = errorParams;
        return this;
    }

    public Error addErrorParamsItem(NameValue errorParamsItem) {
        if (this.errorParams == null) {
            this.errorParams = new ArrayList<NameValue>();
        }
        this.errorParams.add(errorParamsItem);
        return this;
    }

    /**
     * Get errorParams
     *
     * @return errorParams
     **/
    @Schema(description = "")
    public List<NameValue> getErrorParams() {
        return errorParams;
    }

    public void setErrorParams(List<NameValue> errorParams) {
        this.errorParams = errorParams;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Error error = (Error) o;
        return Objects.equals(this.error, error.error) &&
                Objects.equals(this.errorCode, error.errorCode) &&
                Objects.equals(this.errorDescription, error.errorDescription) &&
                Objects.equals(this.errorDeveloperMessage, error.errorDeveloperMessage) &&
                Objects.equals(this.errorUri, error.errorUri) &&
                Objects.equals(this.errorField, error.errorField) &&
                Objects.equals(this.errorParams, error.errorParams);
    }

    @Override
    public int hashCode() {
        return Objects.hash(error, errorCode, errorDescription, errorDeveloperMessage, errorUri, errorField, errorParams);
    }


    @Override
    public String toString() {

        String sb = "class Error {\n" +
                "    error: " + toIndentedString(error) + "\n" +
                "    errorCode: " + toIndentedString(errorCode) + "\n" +
                "    errorDescription: " + toIndentedString(errorDescription) + "\n" +
                "    errorDeveloperMessage: " + toIndentedString(errorDeveloperMessage) + "\n" +
                "    errorUri: " + toIndentedString(errorUri) + "\n" +
                "    errorField: " + toIndentedString(errorField) + "\n" +
                "    errorParams: " + toIndentedString(errorParams) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
