/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * HeaderItem
 */


public class HeaderItem {
    @SerializedName("id")
    private String id = null;

    @SerializedName("aliases")
    private List<Alias> aliases = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("homeUrl")
    private String homeUrl = null;

    @SerializedName("iconUrl")
    private String iconUrl = null;

    @SerializedName("applicationName")
    private String applicationName = null;

    @SerializedName("vendor")
    private String vendor = null;

    public HeaderItem id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public HeaderItem aliases(List<Alias> aliases) {
        this.aliases = aliases;
        return this;
    }

    public HeaderItem addAliasesItem(Alias aliasesItem) {
        if (this.aliases == null) {
            this.aliases = new ArrayList<Alias>();
        }
        this.aliases.add(aliasesItem);
        return this;
    }

    /**
     * Get aliases
     *
     * @return aliases
     **/
    @Schema(description = "")
    public List<Alias> getAliases() {
        return aliases;
    }

    public void setAliases(List<Alias> aliases) {
        this.aliases = aliases;
    }

    public HeaderItem name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public HeaderItem homeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
        return this;
    }

    /**
     * Get homeUrl
     *
     * @return homeUrl
     **/
    @Schema(description = "")
    public String getHomeUrl() {
        return homeUrl;
    }

    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
    }

    public HeaderItem iconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
        return this;
    }

    /**
     * Get iconUrl
     *
     * @return iconUrl
     **/
    @Schema(description = "")
    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public HeaderItem applicationName(String applicationName) {
        this.applicationName = applicationName;
        return this;
    }

    /**
     * Get applicationName
     *
     * @return applicationName
     **/
    @Schema(description = "")
    public String getApplicationName() {
        return applicationName;
    }

    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    public HeaderItem vendor(String vendor) {
        this.vendor = vendor;
        return this;
    }

    /**
     * Get vendor
     *
     * @return vendor
     **/
    @Schema(description = "")
    public String getVendor() {
        return vendor;
    }

    public void setVendor(String vendor) {
        this.vendor = vendor;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        HeaderItem headerItem = (HeaderItem) o;
        return Objects.equals(this.id, headerItem.id) &&
                Objects.equals(this.aliases, headerItem.aliases) &&
                Objects.equals(this.name, headerItem.name) &&
                Objects.equals(this.homeUrl, headerItem.homeUrl) &&
                Objects.equals(this.iconUrl, headerItem.iconUrl) &&
                Objects.equals(this.applicationName, headerItem.applicationName) &&
                Objects.equals(this.vendor, headerItem.vendor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, aliases, name, homeUrl, iconUrl, applicationName, vendor);
    }


    @Override
    public String toString() {

        String sb = "class HeaderItem {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    aliases: " + toIndentedString(aliases) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    homeUrl: " + toIndentedString(homeUrl) + "\n" +
                "    iconUrl: " + toIndentedString(iconUrl) + "\n" +
                "    applicationName: " + toIndentedString(applicationName) + "\n" +
                "    vendor: " + toIndentedString(vendor) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
