/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Jbadetails
 */


public class Jbadetails extends Details {
    @SerializedName("login")
    private String login = null;

    @SerializedName("fullName")
    private String fullName = null;

    @SerializedName("changePasswordUrl")
    private String changePasswordUrl = null;

    public Jbadetails login(String login) {
        this.login = login;
        return this;
    }

    /**
     * Get login
     *
     * @return login
     **/
    @Schema(description = "")
    public String getLogin() {
        return login;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public Jbadetails fullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    /**
     * Get fullName
     *
     * @return fullName
     **/
    @Schema(description = "")
    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Jbadetails changePasswordUrl(String changePasswordUrl) {
        this.changePasswordUrl = changePasswordUrl;
        return this;
    }

    /**
     * Get changePasswordUrl
     *
     * @return changePasswordUrl
     **/
    @Schema(description = "")
    public String getChangePasswordUrl() {
        return changePasswordUrl;
    }

    public void setChangePasswordUrl(String changePasswordUrl) {
        this.changePasswordUrl = changePasswordUrl;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Jbadetails jbadetails = (Jbadetails) o;
        return Objects.equals(this.login, jbadetails.login) &&
                Objects.equals(this.fullName, jbadetails.fullName) &&
                Objects.equals(this.changePasswordUrl, jbadetails.changePasswordUrl) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(login, fullName, changePasswordUrl, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class Jbadetails {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    login: " + toIndentedString(login) + "\n" +
                "    fullName: " + toIndentedString(fullName) + "\n" +
                "    changePasswordUrl: " + toIndentedString(changePasswordUrl) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
