/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * KeyStoreData
 */


public class KeyStoreData {
    @SerializedName("bytes")
    private String bytes = null;

    @SerializedName("password")
    private String password = null;

    public KeyStoreData bytes(String bytes) {
        this.bytes = bytes;
        return this;
    }

    /**
     * Get bytes
     *
     * @return bytes
     **/
    @Schema(description = "")
    public String getBytes() {
        return bytes;
    }

    public void setBytes(String bytes) {
        this.bytes = bytes;
    }

    public KeyStoreData password(String password) {
        this.password = password;
        return this;
    }

    /**
     * Get password
     *
     * @return password
     **/
    @Schema(description = "")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        KeyStoreData keyStoreData = (KeyStoreData) o;
        return Objects.equals(this.bytes, keyStoreData.bytes) &&
                Objects.equals(this.password, keyStoreData.password);
    }

    @Override
    public int hashCode() {
        return Objects.hash(bytes, password);
    }


    @Override
    public String toString() {

        String sb = "class KeyStoreData {\n" +
                "    bytes: " + toIndentedString(bytes) + "\n" +
                "    password: " + toIndentedString(password) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
