/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * LinkData
 */


public class LinkData {
    @SerializedName("id")
    private String id = null;

    @SerializedName("presentation")
    private String presentation = null;

    public LinkData id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public LinkData presentation(String presentation) {
        this.presentation = presentation;
        return this;
    }

    /**
     * Get presentation
     *
     * @return presentation
     **/
    @Schema(description = "")
    public String getPresentation() {
        return presentation;
    }

    public void setPresentation(String presentation) {
        this.presentation = presentation;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        LinkData linkData = (LinkData) o;
        return Objects.equals(this.id, linkData.id) &&
                Objects.equals(this.presentation, linkData.presentation);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, presentation);
    }


    @Override
    public String toString() {

        String sb = "class LinkData {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    presentation: " + toIndentedString(presentation) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
