/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * MigrationsPage
 */


public class MigrationsPage extends BasePage {
    @SerializedName("migrations")
    private List<Migrations> migrations = null;

    public MigrationsPage migrations(List<Migrations> migrations) {
        this.migrations = migrations;
        return this;
    }

    public MigrationsPage addMigrationsItem(Migrations migrationsItem) {
        if (this.migrations == null) {
            this.migrations = new ArrayList<Migrations>();
        }
        this.migrations.add(migrationsItem);
        return this;
    }

    /**
     * Get migrations
     *
     * @return migrations
     **/
    @Schema(description = "")
    public List<Migrations> getMigrations() {
        return migrations;
    }

    public void setMigrations(List<Migrations> migrations) {
        this.migrations = migrations;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MigrationsPage migrationsPage = (MigrationsPage) o;
        return Objects.equals(this.migrations, migrationsPage.migrations) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(migrations, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class MigrationsPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    migrations: " + toIndentedString(migrations) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
