/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Openiddetails
 */


public class Openiddetails extends Details {
    @SerializedName("identifier")
    private String identifier = null;

    @SerializedName("fullName")
    private String fullName = null;

    @SerializedName("avatar")
    private String avatar = null;

    public Openiddetails identifier(String identifier) {
        this.identifier = identifier;
        return this;
    }

    /**
     * Get identifier
     *
     * @return identifier
     **/
    @Schema(description = "")
    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public Openiddetails fullName(String fullName) {
        this.fullName = fullName;
        return this;
    }

    /**
     * Get fullName
     *
     * @return fullName
     **/
    @Schema(description = "")
    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public Openiddetails avatar(String avatar) {
        this.avatar = avatar;
        return this;
    }

    /**
     * Get avatar
     *
     * @return avatar
     **/
    @Schema(description = "")
    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Openiddetails openiddetails = (Openiddetails) o;
        return Objects.equals(this.identifier, openiddetails.identifier) &&
                Objects.equals(this.fullName, openiddetails.fullName) &&
                Objects.equals(this.avatar, openiddetails.avatar) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(identifier, fullName, avatar, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class Openiddetails {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    identifier: " + toIndentedString(identifier) + "\n" +
                "    fullName: " + toIndentedString(fullName) + "\n" +
                "    avatar: " + toIndentedString(avatar) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
