/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * Openidauthmodule
 */


public class Openidauthmodule extends Externalauthmodule {
    @SerializedName("emailSchema")
    private String emailSchema = null;

    @SerializedName("firstNameSchema")
    private String firstNameSchema = null;

    @SerializedName("lastNameSchema")
    private String lastNameSchema = null;

    @SerializedName("fullNameSchema")
    private String fullNameSchema = null;

    @SerializedName("avatarSchema")
    private String avatarSchema = null;

    @SerializedName("urlPattern")
    private String urlPattern = null;

    @SerializedName("iconUrl")
    private String iconUrl = null;

    @SerializedName("emailVerified")
    private Boolean emailVerified = null;

    public Openidauthmodule emailSchema(String emailSchema) {
        this.emailSchema = emailSchema;
        return this;
    }

    /**
     * Get emailSchema
     *
     * @return emailSchema
     **/
    @Schema(description = "")
    public String getEmailSchema() {
        return emailSchema;
    }

    public void setEmailSchema(String emailSchema) {
        this.emailSchema = emailSchema;
    }

    public Openidauthmodule firstNameSchema(String firstNameSchema) {
        this.firstNameSchema = firstNameSchema;
        return this;
    }

    /**
     * Get firstNameSchema
     *
     * @return firstNameSchema
     **/
    @Schema(description = "")
    public String getFirstNameSchema() {
        return firstNameSchema;
    }

    public void setFirstNameSchema(String firstNameSchema) {
        this.firstNameSchema = firstNameSchema;
    }

    public Openidauthmodule lastNameSchema(String lastNameSchema) {
        this.lastNameSchema = lastNameSchema;
        return this;
    }

    /**
     * Get lastNameSchema
     *
     * @return lastNameSchema
     **/
    @Schema(description = "")
    public String getLastNameSchema() {
        return lastNameSchema;
    }

    public void setLastNameSchema(String lastNameSchema) {
        this.lastNameSchema = lastNameSchema;
    }

    public Openidauthmodule fullNameSchema(String fullNameSchema) {
        this.fullNameSchema = fullNameSchema;
        return this;
    }

    /**
     * Get fullNameSchema
     *
     * @return fullNameSchema
     **/
    @Schema(description = "")
    public String getFullNameSchema() {
        return fullNameSchema;
    }

    public void setFullNameSchema(String fullNameSchema) {
        this.fullNameSchema = fullNameSchema;
    }

    public Openidauthmodule avatarSchema(String avatarSchema) {
        this.avatarSchema = avatarSchema;
        return this;
    }

    /**
     * Get avatarSchema
     *
     * @return avatarSchema
     **/
    @Schema(description = "")
    public String getAvatarSchema() {
        return avatarSchema;
    }

    public void setAvatarSchema(String avatarSchema) {
        this.avatarSchema = avatarSchema;
    }

    public Openidauthmodule urlPattern(String urlPattern) {
        this.urlPattern = urlPattern;
        return this;
    }

    /**
     * Get urlPattern
     *
     * @return urlPattern
     **/
    @Schema(description = "")
    public String getUrlPattern() {
        return urlPattern;
    }

    public void setUrlPattern(String urlPattern) {
        this.urlPattern = urlPattern;
    }

    public Openidauthmodule iconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
        return this;
    }

    /**
     * Get iconUrl
     *
     * @return iconUrl
     **/
    @Schema(description = "")
    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    public Openidauthmodule emailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
        return this;
    }

    /**
     * Get emailVerified
     *
     * @return emailVerified
     **/
    @Schema(description = "")
    public Boolean isEmailVerified() {
        return emailVerified;
    }

    public void setEmailVerified(Boolean emailVerified) {
        this.emailVerified = emailVerified;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Openidauthmodule openidauthmodule = (Openidauthmodule) o;
        return Objects.equals(this.emailSchema, openidauthmodule.emailSchema) &&
                Objects.equals(this.firstNameSchema, openidauthmodule.firstNameSchema) &&
                Objects.equals(this.lastNameSchema, openidauthmodule.lastNameSchema) &&
                Objects.equals(this.fullNameSchema, openidauthmodule.fullNameSchema) &&
                Objects.equals(this.avatarSchema, openidauthmodule.avatarSchema) &&
                Objects.equals(this.urlPattern, openidauthmodule.urlPattern) &&
                Objects.equals(this.iconUrl, openidauthmodule.iconUrl) &&
                Objects.equals(this.emailVerified, openidauthmodule.emailVerified) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(emailSchema, firstNameSchema, lastNameSchema, fullNameSchema, avatarSchema, urlPattern, iconUrl, emailVerified, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class Openidauthmodule {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    emailSchema: " + toIndentedString(emailSchema) + "\n" +
                "    firstNameSchema: " + toIndentedString(firstNameSchema) + "\n" +
                "    lastNameSchema: " + toIndentedString(lastNameSchema) + "\n" +
                "    fullNameSchema: " + toIndentedString(fullNameSchema) + "\n" +
                "    avatarSchema: " + toIndentedString(avatarSchema) + "\n" +
                "    urlPattern: " + toIndentedString(urlPattern) + "\n" +
                "    iconUrl: " + toIndentedString(iconUrl) + "\n" +
                "    emailVerified: " + toIndentedString(emailVerified) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
