/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OrganizationRole
 */


public class OrganizationRole {
    @SerializedName("id")
    private String id = null;

    @SerializedName("aliases")
    private List<Alias> aliases = null;

    @SerializedName("role")
    private Role role = null;

    @SerializedName("organization")
    private Organization organization = null;

    @SerializedName("owner")
    private AuthorityHolder owner = null;

    @SerializedName("type")
    private String type = null;

    public OrganizationRole() {
        this.type = this.getClass().getSimpleName();
    }

    public OrganizationRole id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public OrganizationRole aliases(List<Alias> aliases) {
        this.aliases = aliases;
        return this;
    }

    public OrganizationRole addAliasesItem(Alias aliasesItem) {
        if (this.aliases == null) {
            this.aliases = new ArrayList<Alias>();
        }
        this.aliases.add(aliasesItem);
        return this;
    }

    /**
     * Get aliases
     *
     * @return aliases
     **/
    @Schema(description = "")
    public List<Alias> getAliases() {
        return aliases;
    }

    public void setAliases(List<Alias> aliases) {
        this.aliases = aliases;
    }

    public OrganizationRole role(Role role) {
        this.role = role;
        return this;
    }

    /**
     * Get role
     *
     * @return role
     **/
    @Schema(description = "")
    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public OrganizationRole organization(Organization organization) {
        this.organization = organization;
        return this;
    }

    /**
     * Get organization
     *
     * @return organization
     **/
    @Schema(description = "")
    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    public OrganizationRole owner(AuthorityHolder owner) {
        this.owner = owner;
        return this;
    }

    /**
     * Get owner
     *
     * @return owner
     **/
    @Schema(description = "")
    public AuthorityHolder getOwner() {
        return owner;
    }

    public void setOwner(AuthorityHolder owner) {
        this.owner = owner;
    }

    public OrganizationRole type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @Schema(required = true, description = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrganizationRole organizationRole = (OrganizationRole) o;
        return Objects.equals(this.id, organizationRole.id) &&
                Objects.equals(this.aliases, organizationRole.aliases) &&
                Objects.equals(this.role, organizationRole.role) &&
                Objects.equals(this.organization, organizationRole.organization) &&
                Objects.equals(this.owner, organizationRole.owner) &&
                Objects.equals(this.type, organizationRole.type);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, aliases, role, organization, owner, type);
    }


    @Override
    public String toString() {

        String sb = "class OrganizationRole {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    aliases: " + toIndentedString(aliases) + "\n" +
                "    role: " + toIndentedString(role) + "\n" +
                "    organization: " + toIndentedString(organization) + "\n" +
                "    owner: " + toIndentedString(owner) + "\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
