/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * PermanenttokensPage
 */


public class PermanenttokensPage extends BasePage {
    @SerializedName("permanenttokens")
    private List<PermanentToken> permanenttokens = null;

    public PermanenttokensPage permanenttokens(List<PermanentToken> permanenttokens) {
        this.permanenttokens = permanenttokens;
        return this;
    }

    public PermanenttokensPage addPermanenttokensItem(PermanentToken permanenttokensItem) {
        if (this.permanenttokens == null) {
            this.permanenttokens = new ArrayList<PermanentToken>();
        }
        this.permanenttokens.add(permanenttokensItem);
        return this;
    }

    /**
     * Get permanenttokens
     *
     * @return permanenttokens
     **/
    @Schema(description = "")
    public List<PermanentToken> getPermanenttokens() {
        return permanenttokens;
    }

    public void setPermanenttokens(List<PermanentToken> permanenttokens) {
        this.permanenttokens = permanenttokens;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PermanenttokensPage permanenttokensPage = (PermanenttokensPage) o;
        return Objects.equals(this.permanenttokens, permanenttokensPage.permanenttokens) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(permanenttokens, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class PermanenttokensPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    permanenttokens: " + toIndentedString(permanenttokens) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
