/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ProfileAttributePrototype
 */


public class ProfileAttributePrototype {
    @SerializedName("id")
    private String id = null;

    @SerializedName("aliases")
    private List<Alias> aliases = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("type")
    private String type = null;

    @SerializedName("showOnUserList")
    private Boolean showOnUserList = null;

    public ProfileAttributePrototype id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ProfileAttributePrototype aliases(List<Alias> aliases) {
        this.aliases = aliases;
        return this;
    }

    public ProfileAttributePrototype addAliasesItem(Alias aliasesItem) {
        if (this.aliases == null) {
            this.aliases = new ArrayList<Alias>();
        }
        this.aliases.add(aliasesItem);
        return this;
    }

    /**
     * Get aliases
     *
     * @return aliases
     **/
    @Schema(description = "")
    public List<Alias> getAliases() {
        return aliases;
    }

    public void setAliases(List<Alias> aliases) {
        this.aliases = aliases;
    }

    public ProfileAttributePrototype name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ProfileAttributePrototype type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @Schema(description = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public ProfileAttributePrototype showOnUserList(Boolean showOnUserList) {
        this.showOnUserList = showOnUserList;
        return this;
    }

    /**
     * Get showOnUserList
     *
     * @return showOnUserList
     **/
    @Schema(description = "")
    public Boolean isShowOnUserList() {
        return showOnUserList;
    }

    public void setShowOnUserList(Boolean showOnUserList) {
        this.showOnUserList = showOnUserList;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProfileAttributePrototype profileAttributePrototype = (ProfileAttributePrototype) o;
        return Objects.equals(this.id, profileAttributePrototype.id) &&
                Objects.equals(this.aliases, profileAttributePrototype.aliases) &&
                Objects.equals(this.name, profileAttributePrototype.name) &&
                Objects.equals(this.type, profileAttributePrototype.type) &&
                Objects.equals(this.showOnUserList, profileAttributePrototype.showOnUserList);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, aliases, name, type, showOnUserList);
    }


    @Override
    public String toString() {

        String sb = "class ProfileAttributePrototype {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    aliases: " + toIndentedString(aliases) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    showOnUserList: " + toIndentedString(showOnUserList) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
