/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * ProfileAttribute
 */


public class ProfileAttribute {
    @SerializedName("id")
    private String id = null;

    @SerializedName("aliases")
    private List<Alias> aliases = null;

    @SerializedName("value")
    private String value = null;

    @SerializedName("prototype")
    private ProfileAttributePrototype prototype = null;

    public ProfileAttribute id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ProfileAttribute aliases(List<Alias> aliases) {
        this.aliases = aliases;
        return this;
    }

    public ProfileAttribute addAliasesItem(Alias aliasesItem) {
        if (this.aliases == null) {
            this.aliases = new ArrayList<Alias>();
        }
        this.aliases.add(aliasesItem);
        return this;
    }

    /**
     * Get aliases
     *
     * @return aliases
     **/
    @Schema(description = "")
    public List<Alias> getAliases() {
        return aliases;
    }

    public void setAliases(List<Alias> aliases) {
        this.aliases = aliases;
    }

    public ProfileAttribute value(String value) {
        this.value = value;
        return this;
    }

    /**
     * Get value
     *
     * @return value
     **/
    @Schema(description = "")
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public ProfileAttribute prototype(ProfileAttributePrototype prototype) {
        this.prototype = prototype;
        return this;
    }

    /**
     * Get prototype
     *
     * @return prototype
     **/
    @Schema(description = "")
    public ProfileAttributePrototype getPrototype() {
        return prototype;
    }

    public void setPrototype(ProfileAttributePrototype prototype) {
        this.prototype = prototype;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProfileAttribute profileAttribute = (ProfileAttribute) o;
        return Objects.equals(this.id, profileAttribute.id) &&
                Objects.equals(this.aliases, profileAttribute.aliases) &&
                Objects.equals(this.value, profileAttribute.value) &&
                Objects.equals(this.prototype, profileAttribute.prototype);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, aliases, value, prototype);
    }


    @Override
    public String toString() {

        String sb = "class ProfileAttribute {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    aliases: " + toIndentedString(aliases) + "\n" +
                "    value: " + toIndentedString(value) + "\n" +
                "    prototype: " + toIndentedString(prototype) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
