/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Resource
 */


public class Resource {
    @SerializedName("id")
    private String id = null;

    @SerializedName("aliases")
    private List<Alias> aliases = null;

    @SerializedName("key")
    private String key = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("homeUrl")
    private String homeUrl = null;

    @SerializedName("type")
    private String type = null;

    @SerializedName("service")
    private Service service = null;

    @SerializedName("project")
    private Project project = null;

    public Resource id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Resource aliases(List<Alias> aliases) {
        this.aliases = aliases;
        return this;
    }

    public Resource addAliasesItem(Alias aliasesItem) {
        if (this.aliases == null) {
            this.aliases = new ArrayList<Alias>();
        }
        this.aliases.add(aliasesItem);
        return this;
    }

    /**
     * Get aliases
     *
     * @return aliases
     **/
    @Schema(description = "")
    public List<Alias> getAliases() {
        return aliases;
    }

    public void setAliases(List<Alias> aliases) {
        this.aliases = aliases;
    }

    public Resource key(String key) {
        this.key = key;
        return this;
    }

    /**
     * Get key
     *
     * @return key
     **/
    @Schema(description = "")
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public Resource name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     **/
    @Schema(description = "")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Resource homeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
        return this;
    }

    /**
     * Get homeUrl
     *
     * @return homeUrl
     **/
    @Schema(description = "")
    public String getHomeUrl() {
        return homeUrl;
    }

    public void setHomeUrl(String homeUrl) {
        this.homeUrl = homeUrl;
    }

    public Resource type(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @Schema(description = "")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Resource service(Service service) {
        this.service = service;
        return this;
    }

    /**
     * Get service
     *
     * @return service
     **/
    @Schema(description = "")
    public Service getService() {
        return service;
    }

    public void setService(Service service) {
        this.service = service;
    }

    public Resource project(Project project) {
        this.project = project;
        return this;
    }

    /**
     * Get project
     *
     * @return project
     **/
    @Schema(description = "")
    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Resource resource = (Resource) o;
        return Objects.equals(this.id, resource.id) &&
                Objects.equals(this.aliases, resource.aliases) &&
                Objects.equals(this.key, resource.key) &&
                Objects.equals(this.name, resource.name) &&
                Objects.equals(this.homeUrl, resource.homeUrl) &&
                Objects.equals(this.type, resource.type) &&
                Objects.equals(this.service, resource.service) &&
                Objects.equals(this.project, resource.project);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, aliases, key, name, homeUrl, type, service, project);
    }


    @Override
    public String toString() {

        String sb = "class Resource {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    aliases: " + toIndentedString(aliases) + "\n" +
                "    key: " + toIndentedString(key) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    homeUrl: " + toIndentedString(homeUrl) + "\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    service: " + toIndentedString(service) + "\n" +
                "    project: " + toIndentedString(project) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
