/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SourcedorganizationrolesPage
 */


public class SourcedorganizationrolesPage extends BasePage {
    @SerializedName("sourcedorganizationroles")
    private List<SourcedOrganizationRole> sourcedorganizationroles = null;

    public SourcedorganizationrolesPage sourcedorganizationroles(List<SourcedOrganizationRole> sourcedorganizationroles) {
        this.sourcedorganizationroles = sourcedorganizationroles;
        return this;
    }

    public SourcedorganizationrolesPage addSourcedorganizationrolesItem(SourcedOrganizationRole sourcedorganizationrolesItem) {
        if (this.sourcedorganizationroles == null) {
            this.sourcedorganizationroles = new ArrayList<SourcedOrganizationRole>();
        }
        this.sourcedorganizationroles.add(sourcedorganizationrolesItem);
        return this;
    }

    /**
     * Get sourcedorganizationroles
     *
     * @return sourcedorganizationroles
     **/
    @Schema(description = "")
    public List<SourcedOrganizationRole> getSourcedorganizationroles() {
        return sourcedorganizationroles;
    }

    public void setSourcedorganizationroles(List<SourcedOrganizationRole> sourcedorganizationroles) {
        this.sourcedorganizationroles = sourcedorganizationroles;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SourcedorganizationrolesPage sourcedorganizationrolesPage = (SourcedorganizationrolesPage) o;
        return Objects.equals(this.sourcedorganizationroles, sourcedorganizationrolesPage.sourcedorganizationroles) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sourcedorganizationroles, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class SourcedorganizationrolesPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    sourcedorganizationroles: " + toIndentedString(sourcedorganizationroles) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
