/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * SshpublickeysPage
 */


public class SshpublickeysPage extends BasePage {
    @SerializedName("sshpublickeys")
    private List<SshPublicKey> sshpublickeys = null;

    public SshpublickeysPage sshpublickeys(List<SshPublicKey> sshpublickeys) {
        this.sshpublickeys = sshpublickeys;
        return this;
    }

    public SshpublickeysPage addSshpublickeysItem(SshPublicKey sshpublickeysItem) {
        if (this.sshpublickeys == null) {
            this.sshpublickeys = new ArrayList<SshPublicKey>();
        }
        this.sshpublickeys.add(sshpublickeysItem);
        return this;
    }

    /**
     * Get sshpublickeys
     *
     * @return sshpublickeys
     **/
    @Schema(description = "")
    public List<SshPublicKey> getSshpublickeys() {
        return sshpublickeys;
    }

    public void setSshpublickeys(List<SshPublicKey> sshpublickeys) {
        this.sshpublickeys = sshpublickeys;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SshpublickeysPage sshpublickeysPage = (SshpublickeysPage) o;
        return Objects.equals(this.sshpublickeys, sshpublickeysPage.sshpublickeys) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sshpublickeys, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class SshpublickeysPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    sshpublickeys: " + toIndentedString(sshpublickeys) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
