/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * TransitiveprojectrolesPage
 */


public class TransitiveprojectrolesPage extends BasePage {
    @SerializedName("transitiveprojectroles")
    private List<ProjectRole> transitiveprojectroles = null;

    public TransitiveprojectrolesPage transitiveprojectroles(List<ProjectRole> transitiveprojectroles) {
        this.transitiveprojectroles = transitiveprojectroles;
        return this;
    }

    public TransitiveprojectrolesPage addTransitiveprojectrolesItem(ProjectRole transitiveprojectrolesItem) {
        if (this.transitiveprojectroles == null) {
            this.transitiveprojectroles = new ArrayList<ProjectRole>();
        }
        this.transitiveprojectroles.add(transitiveprojectrolesItem);
        return this;
    }

    /**
     * Get transitiveprojectroles
     *
     * @return transitiveprojectroles
     **/
    @Schema(description = "")
    public List<ProjectRole> getTransitiveprojectroles() {
        return transitiveprojectroles;
    }

    public void setTransitiveprojectroles(List<ProjectRole> transitiveprojectroles) {
        this.transitiveprojectroles = transitiveprojectroles;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransitiveprojectrolesPage transitiveprojectrolesPage = (TransitiveprojectrolesPage) o;
        return Objects.equals(this.transitiveprojectroles, transitiveprojectrolesPage.transitiveprojectroles) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(transitiveprojectroles, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class TransitiveprojectrolesPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    transitiveprojectroles: " + toIndentedString(transitiveprojectroles) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
