/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * UntrustedRedirectURI
 */


public class UntrustedRedirectURI {
    @SerializedName("redirectURI")
    private String redirectURI = null;

    @SerializedName("triedFrom")
    private String triedFrom = null;

    @SerializedName("triedAt")
    private Long triedAt = null;

    public UntrustedRedirectURI redirectURI(String redirectURI) {
        this.redirectURI = redirectURI;
        return this;
    }

    /**
     * Get redirectURI
     *
     * @return redirectURI
     **/
    @Schema(description = "")
    public String getRedirectURI() {
        return redirectURI;
    }

    public void setRedirectURI(String redirectURI) {
        this.redirectURI = redirectURI;
    }

    public UntrustedRedirectURI triedFrom(String triedFrom) {
        this.triedFrom = triedFrom;
        return this;
    }

    /**
     * Get triedFrom
     *
     * @return triedFrom
     **/
    @Schema(description = "")
    public String getTriedFrom() {
        return triedFrom;
    }

    public void setTriedFrom(String triedFrom) {
        this.triedFrom = triedFrom;
    }

    public UntrustedRedirectURI triedAt(Long triedAt) {
        this.triedAt = triedAt;
        return this;
    }

    /**
     * Get triedAt
     *
     * @return triedAt
     **/
    @Schema(description = "")
    public Long getTriedAt() {
        return triedAt;
    }

    public void setTriedAt(Long triedAt) {
        this.triedAt = triedAt;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UntrustedRedirectURI untrustedRedirectURI = (UntrustedRedirectURI) o;
        return Objects.equals(this.redirectURI, untrustedRedirectURI.redirectURI) &&
                Objects.equals(this.triedFrom, untrustedRedirectURI.triedFrom) &&
                Objects.equals(this.triedAt, untrustedRedirectURI.triedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(redirectURI, triedFrom, triedAt);
    }


    @Override
    public String toString() {

        String sb = "class UntrustedRedirectURI {\n" +
                "    redirectURI: " + toIndentedString(redirectURI) + "\n" +
                "    triedFrom: " + toIndentedString(triedFrom) + "\n" +
                "    triedAt: " + toIndentedString(triedAt) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
