/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UsersPage
 */


public class UsersPage extends BasePage {
    @SerializedName("users")
    private List<User> users = null;

    public UsersPage users(List<User> users) {
        this.users = users;
        return this;
    }

    public UsersPage addUsersItem(User usersItem) {
        if (this.users == null) {
            this.users = new ArrayList<User>();
        }
        this.users.add(usersItem);
        return this;
    }

    /**
     * Get users
     *
     * @return users
     **/
    @Schema(description = "")
    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UsersPage usersPage = (UsersPage) o;
        return Objects.equals(this.users, usersPage.users) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(users, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class UsersPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    users: " + toIndentedString(users) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
