/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * UserdetailsPage
 */


public class UserdetailsPage extends BasePage {
    @SerializedName("userdetails")
    private List<Details> userdetails = null;

    public UserdetailsPage userdetails(List<Details> userdetails) {
        this.userdetails = userdetails;
        return this;
    }

    public UserdetailsPage addUserdetailsItem(Details userdetailsItem) {
        if (this.userdetails == null) {
            this.userdetails = new ArrayList<Details>();
        }
        this.userdetails.add(userdetailsItem);
        return this;
    }

    /**
     * Get userdetails
     *
     * @return userdetails
     **/
    @Schema(description = "")
    public List<Details> getUserdetails() {
        return userdetails;
    }

    public void setUserdetails(List<Details> userdetails) {
        this.userdetails = userdetails;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserdetailsPage userdetailsPage = (UserdetailsPage) o;
        return Objects.equals(this.userdetails, userdetailsPage.userdetails) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userdetails, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class UserdetailsPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    userdetails: " + toIndentedString(userdetails) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
