/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;

/**
 * UserDashboardImport
 */


public class UserDashboardImport {
    @SerializedName("id")
    private String id = null;

    @SerializedName("user")
    private String user = null;

    @SerializedName("favorite")
    private Boolean favorite = null;

    @SerializedName("ordinal")
    private Integer ordinal = null;

    public UserDashboardImport id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @Schema(description = "")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public UserDashboardImport user(String user) {
        this.user = user;
        return this;
    }

    /**
     * Get user
     *
     * @return user
     **/
    @Schema(description = "")
    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public UserDashboardImport favorite(Boolean favorite) {
        this.favorite = favorite;
        return this;
    }

    /**
     * Get favorite
     *
     * @return favorite
     **/
    @Schema(description = "")
    public Boolean isFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

    public UserDashboardImport ordinal(Integer ordinal) {
        this.ordinal = ordinal;
        return this;
    }

    /**
     * Get ordinal
     *
     * @return ordinal
     **/
    @Schema(description = "")
    public Integer getOrdinal() {
        return ordinal;
    }

    public void setOrdinal(Integer ordinal) {
        this.ordinal = ordinal;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UserDashboardImport userDashboardImport = (UserDashboardImport) o;
        return Objects.equals(this.id, userDashboardImport.id) &&
                Objects.equals(this.user, userDashboardImport.user) &&
                Objects.equals(this.favorite, userDashboardImport.favorite) &&
                Objects.equals(this.ordinal, userDashboardImport.ordinal);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, user, favorite, ordinal);
    }


    @Override
    public String toString() {

        String sb = "class UserDashboardImport {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    user: " + toIndentedString(user) + "\n" +
                "    favorite: " + toIndentedString(favorite) + "\n" +
                "    ordinal: " + toIndentedString(ordinal) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
