/*
 * Hub REST API
 * JetBrains Teamware Connector
 *
 * OpenAPI spec version: 2024.2.38971
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.jetbrains.hub;

import com.google.gson.annotations.SerializedName;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * WidgetsPage
 */


public class WidgetsPage extends BasePage {
    @SerializedName("widgets")
    private List<Widget> widgets = null;

    public WidgetsPage widgets(List<Widget> widgets) {
        this.widgets = widgets;
        return this;
    }

    public WidgetsPage addWidgetsItem(Widget widgetsItem) {
        if (this.widgets == null) {
            this.widgets = new ArrayList<Widget>();
        }
        this.widgets.add(widgetsItem);
        return this;
    }

    /**
     * Get widgets
     *
     * @return widgets
     **/
    @Schema(description = "")
    public List<Widget> getWidgets() {
        return widgets;
    }

    public void setWidgets(List<Widget> widgets) {
        this.widgets = widgets;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WidgetsPage widgetsPage = (WidgetsPage) o;
        return Objects.equals(this.widgets, widgetsPage.widgets) &&
                super.equals(o);
    }

    @Override
    public int hashCode() {
        return Objects.hash(widgets, super.hashCode());
    }


    @Override
    public String toString() {
        String sb = "class WidgetsPage {\n" +
                "    " + toIndentedString(super.toString()) + "\n" +
                "    widgets: " + toIndentedString(widgets) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}
