target: all

server:
  http_listen_port: 4040
  grpc_listen_port: 9095
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  http_server_idle_timeout: 2m
  grpc_server_max_recv_msg_size: 419430400
  grpc_server_max_send_msg_size: 419430400
  log_level: debug

pyroscopedb:
  data_path: /data
  max_block_duration: 1h
  row_group_target_size: 1342177280

tracing:
  enabled: false

limits:
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 2
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30
  max_sessions_per_series: 0
  enforce_labels_order: false
  max_profile_size_bytes: 419430400
  max_profile_stacktrace_samples: 1600000
  max_profile_stacktrace_sample_labels: 1000
  max_profile_stacktrace_depth: 1000
  max_profile_symbol_value_length: 65535
  max_flamegraph_nodes_default: 819200
  max_query_lookback: 100w
  max_query_length: 1d
  reject_older_than: 0
  reject_newer_than: 0

storage:
  filesystem:
    dir: /data-shared

self_profiling:
  disable_push: true

analytics:
  reporting_enabled: false

show_banner: false