name: start-a-local-youtrack
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  start-a-local-youtrack:
    runs-on: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: docker pull
        run: docker pull jetbrains/youtrack:2024.2.38971