name: step 03 restore a backup demo_project
on:
  workflow_dispatch:

jobs:
  step-03-restore-a-backup-demo_project:
    runs-on: self-hosted
    steps:
      - uses: actions/cache/restore@v3
        name: youtrack_data
        id: youtrack_data
        with:
          path: ./backup/demo_project/youtrack_data.tar
          key: backup-youtrack_data
          fail-on-cache-miss: true
      - uses: actions/cache/restore@v3
        name: youtrack_conf
        id: youtrack_conf
        with:
          path: ./backup/demo_project/youtrack_conf.tar
          key: backup-youtrack_conf
          fail-on-cache-miss: true


      - name: extract youtrack_data
        env:
          DIR: youtrack_data
          STEP: demo_project
        run: |
          sudo ls -la ./volumes || true
          sudo ls -la ./volumes/${DIR} || true
          sudo rm -rf ./volumes/${DIR} || true
          sudo tar xf ./backup/${STEP}/${DIR}.tar -C .
          sudo ls -la ./volumes
          sudo ls -la ./volumes/${DIR} || true

      - name: extract youtrack_conf
        env:
          DIR: youtrack_conf
          STEP: demo_project
        run: |
          sudo ls -la ./volumes || true
          sudo ls -la ./volumes/${DIR} || true
          sudo rm -rf ./volumes/${DIR} || true
          sudo tar xf ./backup/${STEP}/${DIR}.tar -C .
          sudo ls -la ./volumes
          sudo ls -la ./volumes/${DIR} || true
